In [25]:
import pandas as pd

df_merged = pd.read_csv('/content/protoforms_final.tsv', delimiter='\t')

In [26]:
df_merged.sort_values(by=['LANGUAGE', 'GLOSS'], inplace=True)
display(df_merged.head())

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
78,I,I,1209.0,Proto-Arawakan,araw1281,Arawakan,nʊ,n ʊ
79,I,I,1209.0,Proto-Arawakan,araw1281,Arawakan,nʊ,n ʊ
0,acid,SOUR,1906.0,Proto-Arawakan,araw1281,Arawakan,kadama,k a d a m a
1,acid,SOUR,1906.0,Proto-Arawakan,araw1281,Arawakan,kadama,k a d a m a
2,animal,ANIMAL,619.0,Proto-Arawakan,araw1281,Arawakan,pɨra,p ɨ r a

In [27]:
df_original = df_merged.copy()
df_merged.drop_duplicates(subset=['CONCEPTICON_GLOSS', 'GLOTTOCODE', 'TOKENS'], inplace=True)

df_dropped = df_original[~df_original.index.isin(df_merged.index)]

display(df_merged.head())

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
78,I,I,1209.0,Proto-Arawakan,araw1281,Arawakan,nʊ,n ʊ
0,acid,SOUR,1906.0,Proto-Arawakan,araw1281,Arawakan,kadama,k a d a m a
2,animal,ANIMAL,619.0,Proto-Arawakan,araw1281,Arawakan,pɨra,p ɨ r a
4,arm,ARM OR HAND,2121.0,Proto-Arawakan,araw1281,Arawakan,kanʊ,k a n ʊ
6,arm,ARM OR HAND,2121.0,Proto-Arawakan,araw1281,Arawakan,dana,d a n a

In [28]:
df_merged.to_csv('merged_sorted_dataset.tsv', index=False, sep='\t')
df_dropped.to_csv('protoforms_dropped.tsv', index=False, sep='\t')