In [74]:
import pandas as pd

file_path = 'forms.csv'
df = pd.read_csv(file_path, sep=',', engine='python')
display(df.head())

file_path = 'languages.csv'
df = pd.read_csv(file_path, sep=',', engine='python')
display(df.head())

file_path = 'parameters.csv'
df = pd.read_csv(file_path, sep=',', engine='python')
display(df.head())

,ID,Local_ID,Language_ID,Parameter_ID,Value,Form,Segments,Comment,Source,Cognacy,Loan,Graphemes,Profile
0,Achagua-1_i-1,NaN,Achagua,1_i,nuya,nuya,n u j a,NaN,walker2011,NaN,NaN,^n u y a$,default
1,Yanesha-1_i-1,NaN,Yanesha,1_i,na,na,n a,NaN,walker2011,NaN,NaN,^n a$,default
2,Anauya-1_i-1,NaN,Anauya,1_i,nu,nu,n u,NaN,walker2011,NaN,NaN,^n u$,default
3,Apurina-1_i-1,NaN,Apurina,1_i,nota,nota,n o t a,NaN,walker2011,NaN,NaN,^n o t a$,default
4,Aruan-1_i-1,NaN,Aruan,1_i,nuy,nuy,n u y,NaN,walker2011,NaN,NaN,^n u y$,default

,ID,Name,Glottocode,Glottolog_Name,ISO639P3code,Macroarea,Latitude,Longitude,Family,Full_Name
0,Achagua,Achagua,acha1250,Achagua,aca,South America,4.42,-72.25,Arawakan,Achagua
1,Anauya,Anauyá,anau1243,Anauyá,NaN,South America,-2.00,-66.00,Arawakan,Anauya
2,Apurina,Apurinã,apur1254,Apurinã,apu,South America,-9.00,-67.00,Arawakan,Apurina (Apurinã)
3,Araicu,Araicu,arai1239,Araicu,NaN,South America,-3.10,-67.90,Arawakan,Waraicu
4,Aruan,Aruan,arua1264,Aruan,NaN,South America,0.00,-50.00,Arawakan,Arua (Aruã)

       ID  Name  Concepticon_ID Concepticon_Gloss
0     1_i     I            1209                 I
1   2_you   you            1213               YOU
2    3_we    we            1212                WE
3  4_this  this            1214              THIS
4  5_that  that              78              THAT

In [75]:
# Assuming the dataframes are already loaded as df_forms, df_languages, and df_parameters
# If not, load them first
df_forms = pd.read_csv('forms.csv', sep=',', engine='python')
df_languages = pd.read_csv('languages.csv', sep=',', engine='python')
df_parameters = pd.read_csv('parameters.csv', sep=',', engine='python')
#df_cognates = pd.read_csv('cognates.csv', sep=',', engine='python')

# Join df_forms and df_languages on forms.Language_ID = languages.ID
merged_df = pd.merge(df_forms, df_languages, left_on='Language_ID', right_on='ID', how='inner', suffixes=('_forms', '_languages'))

# Join the result with df_parameters on forms.Parameter_ID = parameters.ID
final_df = pd.merge(merged_df, df_parameters, left_on='Parameter_ID', right_on='ID', how='inner', suffixes=('', '_parameters'))

# Display the first few rows of the final joined dataframe
pd.set_option('display.max_columns', None)
display(final_df.head())
display(final_df.tail())

,ID_forms,Local_ID,Language_ID,Parameter_ID,Value,Form,Segments,Comment,Source,Cognacy,Loan,Graphemes,Profile,ID_languages,Name,Glottocode,Glottolog_Name,ISO639P3code,Macroarea,Latitude,Longitude,Family,Full_Name,ID,Name_parameters,Concepticon_ID,Concepticon_Gloss
0,Achagua-1_i-1,NaN,Achagua,1_i,nuya,nuya,n u j a,NaN,walker2011,NaN,NaN,^n u y a$,default,Achagua,Achagua,acha1250,Achagua,aca,South America,4.42,-72.25,Arawakan,Achagua,1_i,I,1209,I
1,Yanesha-1_i-1,NaN,Yanesha,1_i,na,na,n a,NaN,walker2011,NaN,NaN,^n a$,default,Yanesha,Yanesha',yane1238,Yanesha',ame,South America,-10.50,-75.42,Arawakan,Amuesha (Yanesha'),1_i,I,1209,I
2,Anauya-1_i-1,NaN,Anauya,1_i,nu,nu,n u,NaN,walker2011,NaN,NaN,^n u$,default,Anauya,Anauyá,anau1243,Anauyá,NaN,South America,-2.00,-66.00,Arawakan,Anauya,1_i,I,1209,I
3,Apurina-1_i-1,NaN,Apurina,1_i,nota,nota,n o t a,NaN,walker2011,NaN,NaN,^n o t a$,default,Apurina,Apurinã,apur1254,Apurinã,apu,South America,-9.00,-67.00,Arawakan,Apurina (Apurinã),1_i,I,1209,I
4,Aruan-1_i-1,NaN,Aruan,1_i,nuy,nuy,n u y,NaN,walker2011,NaN,NaN,^n u y$,default,Aruan,Aruan,arua1264,Aruan,NaN,South America,0.00,-50.00,Arawakan,Arua (Aruã),1_i,I,1209,I

,ID_forms,Local_ID,Language_ID,Parameter_ID,Value,Form,Segments,Comment,Source,Cognacy,Loan,Graphemes,Profile,ID_languages,Name,Glottocode,Glottolog_Name,ISO639P3code,Macroarea,Latitude,Longitude,Family,Full_Name,ID,Name_parameters,Concepticon_ID,Concepticon_Gloss
5889,WarekenaVelha-100_name-1,NaN,WarekenaVelha,100_name,ʃina,ʃina,ʃ i n a,NaN,walker2011,NaN,NaN,^ʃ i n a$,default,WarekenaVelha,Warekena Velha,ware1255,Warekena do San Miguel,NaN,South America,1.50,-67.5,Arawakan,Warekena,100_name,name,1405,NAME
5890,Waura-100_name-1,NaN,Waura,100_name,-kupɨna,-kupɨna,k u p ɨ n a,NaN,walker2011,NaN,NaN,^- k u p ɨ n a$,default,Waura,Waurá,waur1244,Waurá,wau,South America,-12.40,-53.6,Arawakan,Waura (Waurá),100_name,name,1405,NAME
5891,Yavitero-100_name-1,NaN,Yavitero,100_name,iliwanaha,iliwanaha,i l i w a n a h a,NaN,walker2011,NaN,NaN,^i l i w a n a h a$,default,Yavitero,Yavitero,yavi1244,Yavitero-Pareni,yvt,South America,2.40,-67.5,Arawakan,Yavitero (Paraene),100_name,name,1405,NAME
5892,Yawalapiti-100_name-1,NaN,Yawalapiti,100_name,kipina,kipina,k i p i n a,NaN,walker2011,NaN,NaN,^k i p i n a$,default,Yawalapiti,Yawalapití,yawa1261,Yawalapití,yaw,South America,-12.20,-53.3,Arawakan,Yawalapiti (Yawalapití),100_name,name,1405,NAME
5893,Yucuna-100_name-1,NaN,Yucuna,100_name,iihi,iihi,iː h i,NaN,walker2011,NaN,NaN,^ii h i$,default,Yucuna,Yucuna,yucu1253,Yucuna,ycn,South America,-0.75,-71.0,Arawakan,Yukuna (Matapi),100_name,name,1405,NAME

In [76]:
print(final_df.columns.tolist())

['ID_forms', 'Local_ID', 'Language_ID', 'Parameter_ID', 'Value', 'Form', 'Segments', 'Comment', 'Source', 'Cognacy', 'Loan', 'Graphemes', 'Profile', 'ID_languages', 'Name', 'Glottocode', 'Glottolog_Name', 'ISO639P3code', 'Macroarea', 'Latitude', 'Longitude', 'Family', 'Full_Name', 'ID', 'Name_parameters', 'Concepticon_ID', 'Concepticon_Gloss']

In [77]:
columns_to_keep = [
    'Form',
    'Segments',
    'Name',
    'Glottocode',
    'Glottolog_Name',
    'Family',
    'Name_parameters',
    'Concepticon_ID',
    'Concepticon_Gloss'
]

# Create a new DataFrame with only the specified columns
df_subset = final_df[columns_to_keep].copy()

# Display the first few rows of the new DataFrame
display(df_subset.head())

,Form,Segments,Name,Glottocode,Glottolog_Name,Family,Name_parameters,Concepticon_ID,Concepticon_Gloss
0,nuya,n u j a,Achagua,acha1250,Achagua,Arawakan,I,1209,I
1,na,n a,Yanesha',yane1238,Yanesha',Arawakan,I,1209,I
2,nu,n u,Anauyá,anau1243,Anauyá,Arawakan,I,1209,I
3,nota,n o t a,Apurinã,apur1254,Apurinã,Arawakan,I,1209,I
4,nuy,n u y,Aruan,arua1264,Aruan,Arawakan,I,1209,I

In [78]:
# Define the new order and names for the columns
new_column_order_and_names = {
    'Name_parameters': 'GLOSS',
    'Concepticon_Gloss': 'CONCEPTICON_GLOSS',
    'Concepticon_ID': 'CONCEPTICON_ID',
    'Name': 'LANGUAGE',
    'Glottocode': 'GLOTTOCODE',
    'Family': 'FAMILY',
    'Form': 'FORM',
    'Segments': 'TOKENS'
}

# Select, reorder, and rename the columns
df_reordered_renamed = df_subset[list(new_column_order_and_names.keys())].rename(columns=new_column_order_and_names)

# Display the first few rows of the new DataFrame
display(df_reordered_renamed.head())

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,I,I,1209,Achagua,acha1250,Arawakan,nuya,n u j a
1,I,I,1209,Yanesha',yane1238,Arawakan,na,n a
2,I,I,1209,Anauyá,anau1243,Arawakan,nu,n u
3,I,I,1209,Apurinã,apur1254,Arawakan,nota,n o t a
4,I,I,1209,Aruan,arua1264,Arawakan,nuy,n u y

In [79]:
# Save the DataFrame as a TSV file
df_reordered_renamed.to_csv('walkerarawakan.tsv', sep='\t', index=False)