# Task
Merge the datasets "lexibank_final.tsv" and "hgn_final.tsv", then sort the merged dataset alphabetically by the 'language' column and then by the 'gloss' column.

## Load the datasets

### Subtask:
Load the `lexibank_final.tsv` and `hgn_final.tsv` datasets into pandas DataFrames.

**Reasoning**:
The subtask is to load two TSV files into pandas DataFrames. This can be done by importing pandas and then using `pd.read_csv` for each file with the tab delimiter.

In [1]:
import pandas as pd

df_lexibank = pd.read_csv('/content/lexibank_final.tsv', delimiter='\t')
df_hgn = pd.read_csv('/content/hgn_final.tsv', delimiter='\t')

## Merge the datasets

### Subtask:
Merge the two DataFrames based on common columns.

**Reasoning**:
Merge the two dataframes based on common columns using an outer merge to keep all rows.

In [2]:
common_cols = list(set(df_lexibank.columns) & set(df_hgn.columns))
df_merged = pd.merge(df_lexibank, df_hgn, on=common_cols, how='outer')
display(df_merged.head())

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,a little,A LITTLE,2924.0,Koretu,cure1236,Tucanoan,yóḥe̠,j ɔ h ɛ
1,a little,A LITTLE,2924.0,Koretu,cure1236,Tucanoan,yóḥe̠,j ɔ h ɛ
2,a little,A LITTLE,2924.0,Desano,desa1247,Tucanoan,āminiḗ̠ga,a a m i n i ɛ ɛ g a
3,a little,A LITTLE,2924.0,Desano,desa1247,Tucanoan,āminiḗ̠ga,a a m i n i ɛ ɛ g a
4,a little,A LITTLE,2924.0,Yupua,jupu1235,Tucanoan,siáaya,s i a a j a

## Sort the merged dataset

### Subtask:
Sort the merged DataFrame alphabetically by the 'language' column and then by the 'gloss' column.

**Reasoning**:
Sort the merged DataFrame by the 'LANGUAGE' column and then by the 'GLOSS' column and then display the head of the sorted DataFrame to verify the sorting.

In [3]:
df_merged.sort_values(by=['LANGUAGE', 'GLOSS'], inplace=True)
display(df_merged.head())

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
1212,ALL,ALL,98.0,AWETI,awet1244,Tupian,momati,m o m a t i
1213,ALL,ALL,98.0,AWETI,awet1244,Tupian,momati,m o m a t i
3221,ARM,ARM,1673.0,AWETI,awet1244,Tupian,kɨwa,k ɨ w a
3222,ARM,ARM,1673.0,AWETI,awet1244,Tupian,kɨwa,k ɨ w a
5376,AXE,AXE,677.0,AWETI,awet1244,Tupian,kɨ,k ɨ

## Display the result

### Subtask:
Display the first few rows of the merged and sorted DataFrame.

**Reasoning**:
Display the first few rows of the merged and sorted DataFrame as requested by the subtask.

In [4]:
display(df_merged.head())

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
1212,ALL,ALL,98.0,AWETI,awet1244,Tupian,momati,m o m a t i
1213,ALL,ALL,98.0,AWETI,awet1244,Tupian,momati,m o m a t i
3221,ARM,ARM,1673.0,AWETI,awet1244,Tupian,kɨwa,k ɨ w a
3222,ARM,ARM,1673.0,AWETI,awet1244,Tupian,kɨwa,k ɨ w a
5376,AXE,AXE,677.0,AWETI,awet1244,Tupian,kɨ,k ɨ

## Summary:

### Data Analysis Key Findings
* The `lexibank_final.tsv` and `hgn_final.tsv` datasets were successfully loaded into pandas DataFrames.
* The two DataFrames were merged using an outer join based on common columns.
* The merged DataFrame was sorted alphabetically first by the 'LANGUAGE' column and then by the 'GLOSS' column.

### Insights or Next Steps
* The merged and sorted dataset is now ready for further analysis or processing based on the specific requirements of the study involving these linguistic data.
* Depending on the analytical goals, the next steps could involve filtering, aggregation, or visualization of the merged data.

## Remove duplicate rows

### Subtask:
Remove duplicate rows from the merged and sorted DataFrame.

**Reasoning**:
Use the `drop_duplicates()` method to remove duplicate rows from the merged DataFrame and then display the head of the resulting DataFrame to verify the removal of duplicates.

In [9]:
df_merged.drop_duplicates(subset=['CONCEPTICON_GLOSS', 'GLOTTOCODE', 'TOKENS'], inplace=True)
display(df_merged.head())

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
1212,ALL,ALL,98.0,AWETI,awet1244,Tupian,momati,m o m a t i
3221,ARM,ARM,1673.0,AWETI,awet1244,Tupian,kɨwa,k ɨ w a
5376,AXE,AXE,677.0,AWETI,awet1244,Tupian,kɨ,k ɨ
7889,BASKET,BASKET,1539.0,AWETI,awet1244,Tupian,mãjãku,m ã j ã k u
10411,BELLY,BELLY,1251.0,AWETI,awet1244,Tupian,pɨlup,p ɨ l u p

In [10]:
df_merged.to_csv('merged_sorted_dataset.tsv', index=False, sep='\t')