Generar lista de lenguas + códigos

In [2]:
from bs4 import BeautifulSoup
import csv

# Carga el HTML descargado localmente
with open("south_america.txt", "r", encoding="utf-8") as f:
    html = f.read()

soup = BeautifulSoup(html, 'html.parser')
output = []

# Encuentra todas las familias dentro de South America
accordion_groups = soup.select('div.accordion-group')

for group in accordion_groups:
    # Extrae el nombre de la familia
    family_tag = group.select_one('.accordion-heading a')
    if not family_tag:
        continue
    family_name = family_tag.get_text(strip=True).split('(')[0].strip()

    # Encuentra todas las lenguas dentro de esa familia
    language_links = group.select('.accordion-inner a[href^="/languages/language/"]')

    for lang_tag in language_links:
        lang_name = lang_tag.get_text(strip=True)
        href = lang_tag.get('href')
        lang_id = href.split('/')[-1]
        output.append((family_name, lang_name, lang_id))

# Guardar como CSV
with open("south_american_languages.csv", "w", encoding="utf-8", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["Family", "Language", "ID"])
    writer.writerows(output)

print("✅ Datos extraídos y guardados en south_american_languages.csv")

✅ Datos extraídos y guardados en south_american_languages.csv

Descargar todas las páginas por ID

In [3]:
import os
import time
import requests

output_dir = 'pages'
base_url = "https://huntergatherer.la.utexas.edu/languages/language/{}"  # ID

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

ids = []
with open('south_american_languages.csv', newline='', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    for row in reader:
        ids.append(row['ID'].strip())

for lang_id in ids:
    url = base_url.format(lang_id)
    dest = os.path.join(output_dir, f"{lang_id}.html")

    if os.path.exists(dest):
        print(f"✔️ Ya descargado: {lang_id}")
        continue

    try:
        print(f"⬇️ Descargando {url}")
        response = requests.get(url)
        response.raise_for_status()
        with open(dest, 'w', encoding='utf-8') as f:
            f.write(response.text)
        time.sleep(1)  # Para evitar sobrecargar el servidor
    except Exception as e:
        print(f"❌ Error al descargar {lang_id}: {e}")

⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/265
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/48
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/257
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/50
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/406
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/51
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/474
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/52
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/53
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/253
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/408
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/343
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/410
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/54
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/252
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/405
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/407
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/55
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/56
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/411
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/254
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/409
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/255
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/57
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/58
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/59
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/60
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/344
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/61
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/473
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/349
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/63
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/49
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/64
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/404
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/65
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/475
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/413
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/412
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/414
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/415
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/416
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/98
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/418
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/350
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/417
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/68
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/69
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/420
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/419
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/70
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/71
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/351
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/72
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/73
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/354
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/421
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/258
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/75
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/76
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/422
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/424
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/77
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/353
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/423
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/78
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/79
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/352
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/80
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/81
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/427
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/425
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/426
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/371
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/355
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/430
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/432
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/83
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/84
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/431
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/476
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/88
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/262
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/85
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/86
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/82
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/263
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/428
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/429
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/477
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/114
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/115
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/116
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/479
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/478
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/434
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/356
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/90
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/87
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/401
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/402
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/92
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/93
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/94
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/95
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/96
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/389
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/390
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/391
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/436
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/435
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/480
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/439
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/97
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/66
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/99
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/100
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/377
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/101
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/102
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/378
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/440
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/379
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/104
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/380
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/381
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/437
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/438
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/106
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/107
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/108
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/67
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/109
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/111
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/382
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/112
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/103
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/113
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/441
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/117
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/118
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/442
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/400
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/444
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/385
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/387
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/91
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/386
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/443
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/384
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/392
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/393
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/394
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/396
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/397
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/398
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/395
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/433
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/119
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/120
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/121
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/122
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/123
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/445
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/451
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/362
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/357
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/448
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/447
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/358
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/449
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/446
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/487
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/124
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/359
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/360
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/361
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/125
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/126
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/127
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/128
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/129
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/452
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/130
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/363
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/372
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/375
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/373
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/403
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/374
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/110
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/131
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/132
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/133
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/134
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/135
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/146
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/144
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/453
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/147
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/136
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/148
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/149
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/138
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/139
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/140
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/141
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/142
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/137
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/143
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/145
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/154
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/457
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/456
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/365
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/467
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/454
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/469
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/369
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/151
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/462
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/268
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/461
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/464
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/458
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/455
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/152
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/267
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/465
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/468
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/463
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/368
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/150
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/460
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/470
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/466
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/364
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/459
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/388
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/266
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/156
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/157
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/158
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/159
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/160
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/161
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/162
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/399
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/472
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/471
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/163
⬇️ Descargando https://huntergatherer.la.utexas.edu/languages/language/370

In [8]:
import os
import csv
import time
import traceback
from bs4 import BeautifulSoup

INPUT_CSV = "south_american_languages.csv"
OUTPUT_CSV = "basic_vocabulary_full.csv"
HTML_DIR = "pages"  # Directorio donde están los HTML descargados

COLUMNS = [
    "Gloss Link", "English Gloss", "Spanish Gloss", "Portuguese Gloss", "Orthographic Form", "Phonemicized Form", "Gloss as in Source",
    "Etymology Code", "Proto-Form", "Proto-Language", "Loan Source",
    "Wanderwort Status", "Etyma Set", "Etymology Notes", "General Notes", "Source"
]

def get_basic_vocab_from_file(lang_id):
    filepath = os.path.join(HTML_DIR, f"{lang_id}.html")

    if not os.path.exists(filepath):
        print(f"❌ Archivo no encontrado para ID {lang_id}")
        return []

    with open(filepath, 'r', encoding='utf-8') as f:
        html = f.read()

    soup = BeautifulSoup(html, 'html.parser')

    basic_section = soup.find('div', id='basic_frame')
    if not basic_section:
        print(f"⚠️ Advertencia: No se encontró la sección básica para ID {lang_id}")
        return []

    table = basic_section.find('table')
    if not table:
        print(f"⚠️ Advertencia: No se encontró la tabla de vocabulario para ID {lang_id}")
        return []

    rows = table.select('tbody tr')
    if not rows:
        print(f"⚠️ Advertencia: Tabla vacía para ID {lang_id}")
        return []

    data_rows = []
    for row in rows:
        cells = row.find_all('td')
        # We now expect more columns due to separate glosses, let's adjust the check
        if len(cells) < 14: # Minimum expected cells based on other columns
            print(f"⚠️ Fila ignorada con menos de {len(COLUMNS) - 3} celdas (excluding glosses) en ID {lang_id}")
            continue

        # Extract Gloss Link from the first cell
        a_tag = cells[0].find('a')
        gloss_link = a_tag['href'] if a_tag else ''

        # Extract different language glosses from the first cell
        english_gloss = ""
        spanish_gloss = ""
        portuguese_gloss = ""

        # Assuming glosses are within specific tags or identifiable patterns within the first <td>
        # This part might need adjustment based on actual HTML structure
        # Let's try to find spans with potential language indicators or just extract all text and try to split
        gloss_text = cells[0].get_text(separator=' | ', strip=True)
        # A simple split by ' | ' might not be robust, but let's try to see the structure first
        glosses = [g.strip() for g in gloss_text.split('|')]

        # This is a basic attempt. We might need more sophisticated parsing
        if len(glosses) > 0:
            english_gloss = glosses[0]
        if len(glosses) > 1:
            spanish_gloss = glosses[1]
        if len(glosses) > 2:
            portuguese_gloss = glosses[2]


        # Extract other columns - adjust starting index and count based on the new gloss columns
        # We now have Gloss Link, English, Spanish, Portuguese Glosses, so the next column starts from index 4
        others = [cell.get_text(strip=True) for cell in cells[1:14]] # Still extracting up to 14 cells for now

        # Combine all extracted data
        data_rows.append([gloss_link, english_gloss, spanish_gloss, portuguese_gloss] + others)

    print(f"✅ {len(data_rows)} entradas extraídas para ID {lang_id}")
    return data_rows

def main():
    all_data = []

    with open(INPUT_CSV, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            family = row['Family']
            language = row['Language']
            lang_id = row['ID']

            try:
                print(f"📄 Procesando {language} (ID: {lang_id})...")
                entries = get_basic_vocab_from_file(lang_id)
                if entries:
                    for entry in entries:
                        full_row = [family, language, lang_id] + entry
                        all_data.append(full_row)
                else:
                    print(f"⚠️ No se encontraron entradas para {language} (ID {lang_id})")
            except Exception as e:
                print(f"❌ Error procesando {language} ({lang_id}): {e}")
                traceback.print_exc()

    if all_data:
        with open(OUTPUT_CSV, "w", newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow(["Family", "Language", "ID"] + COLUMNS)
            writer.writerows(all_data)
        print(f"✅ Datos guardados en {OUTPUT_CSV}")
    else:
        print("⚠️ No se encontraron datos para guardar.")

if __name__ == "__main__":
    main()

📄 Procesando Mapudungun (ID: 265)...
✅ 191 entradas extraídas para ID 265
📄 Procesando Achagua (ID: 48)...
✅ 191 entradas extraídas para ID 48
📄 Procesando Añun (ID: 257)...
⚠️ Advertencia: No se encontró la sección básica para ID 257
⚠️ No se encontraron entradas para Añun (ID 257)
📄 Procesando Apurinã (ID: 50)...
⚠️ Advertencia: No se encontró la sección básica para ID 50
⚠️ No se encontraron entradas para Apurinã (ID 50)
📄 Procesando Asháninka (ID: 406)...
⚠️ Advertencia: No se encontró la sección básica para ID 406
⚠️ No se encontraron entradas para Asháninka (ID 406)
📄 Procesando Asheninka Apurucayali (ID: 51)...
⚠️ Advertencia: No se encontró la sección básica para ID 51
⚠️ No se encontraron entradas para Asheninka Apurucayali (ID 51)
📄 Procesando Bahuana (ID: 474)...
⚠️ Advertencia: No se encontró la sección básica para ID 474
⚠️ No se encontraron entradas para Bahuana (ID 474)
📄 Procesando Baniwa (ID: 52)...
✅ 192 entradas extraídas para ID 52
📄 Procesando Bare (ID: 53)...
✅ 191 entradas extraídas para ID 53
📄 Procesando Baure (ID: 253)...
✅ 191 entradas extraídas para ID 253
📄 Procesando Caquinte (ID: 408)...
⚠️ Advertencia: No se encontró la sección básica para ID 408
⚠️ No se encontraron entradas para Caquinte (ID 408)
📄 Procesando Ignaciano (ID: 343)...
✅ 191 entradas extraídas para ID 343
📄 Procesando Iñapari (ID: 410)...
⚠️ Advertencia: No se encontró la sección básica para ID 410
⚠️ No se encontraron entradas para Iñapari (ID 410)
📄 Procesando Kabiyari (ID: 54)...
✅ 191 entradas extraídas para ID 54
📄 Procesando Kinikinau (ID: 252)...
⚠️ Advertencia: No se encontró la sección básica para ID 252
⚠️ No se encontraron entradas para Kinikinau (ID 252)
📄 Procesando Lokono (ID: 405)...
✅ 192 entradas extraídas para ID 405
📄 Procesando Machiguenga (ID: 407)...
⚠️ Advertencia: No se encontró la sección básica para ID 407
⚠️ No se encontraron entradas para Machiguenga (ID 407)
📄 Procesando Maipure (ID: 55)...
⚠️ Advertencia: No se encontró la sección básica para ID 55
⚠️ No se encontraron entradas para Maipure (ID 55)
📄 Procesando Mandawaka (ID: 56)...
✅ 191 entradas extraídas para ID 56
📄 Procesando Manxineri (ID: 411)...
⚠️ Advertencia: No se encontró la sección básica para ID 411
⚠️ No se encontraron entradas para Manxineri (ID 411)
📄 Procesando Nanti (ID: 254)...
⚠️ Advertencia: No se encontró la sección básica para ID 254
⚠️ No se encontraron entradas para Nanti (ID 254)
📄 Procesando Nomatsigenga (ID: 409)...
⚠️ Advertencia: No se encontró la sección básica para ID 409
⚠️ No se encontraron entradas para Nomatsigenga (ID 409)
📄 Procesando Palikur (ID: 255)...
⚠️ Advertencia: No se encontró la sección básica para ID 255
⚠️ No se encontraron entradas para Palikur (ID 255)
📄 Procesando Paresi (ID: 57)...
✅ 191 entradas extraídas para ID 57
📄 Procesando Piapoco (ID: 58)...
✅ 191 entradas extraídas para ID 58
📄 Procesando Resígaro (ID: 59)...
✅ 192 entradas extraídas para ID 59
📄 Procesando Tariana (ID: 60)...
✅ 192 entradas extraídas para ID 60
📄 Procesando Trinitario (ID: 344)...
✅ 191 entradas extraídas para ID 344
📄 Procesando Wapishana (ID: 61)...
✅ 191 entradas extraídas para ID 61
📄 Procesando Warekena do Xié (ID: 473)...
⚠️ Advertencia: No se encontró la sección básica para ID 473
⚠️ No se encontraron entradas para Warekena do Xié (ID 473)
📄 Procesando Waurá (ID: 349)...
✅ 191 entradas extraídas para ID 349
📄 Procesando Wayuu (ID: 63)...
✅ 191 entradas extraídas para ID 63
📄 Procesando Yanesha' (ID: 49)...
⚠️ Advertencia: No se encontró la sección básica para ID 49
⚠️ No se encontraron entradas para Yanesha' (ID 49)
📄 Procesando Yavitero (ID: 64)...
✅ 191 entradas extraídas para ID 64
📄 Procesando Yine (ID: 404)...
✅ 191 entradas extraídas para ID 404
📄 Procesando Yukuna (ID: 65)...
✅ 192 entradas extraídas para ID 65
📄 Procesando Banawa (ID: 475)...
⚠️ Advertencia: No se encontró la sección básica para ID 475
⚠️ No se encontraron entradas para Banawa (ID 475)
📄 Procesando Dení (ID: 413)...
⚠️ Advertencia: No se encontró la sección básica para ID 413
⚠️ No se encontraron entradas para Dení (ID 413)
📄 Procesando Jarawara (ID: 412)...
⚠️ Advertencia: No se encontró la sección básica para ID 412
⚠️ No se encontraron entradas para Jarawara (ID 412)
📄 Procesando Kulina (ID: 414)...
⚠️ Advertencia: No se encontró la sección básica para ID 414
⚠️ No se encontraron entradas para Kulina (ID 414)
📄 Procesando Paumarí (ID: 415)...
⚠️ Advertencia: No se encontró la sección básica para ID 415
⚠️ No se encontraron entradas para Paumarí (ID 415)
📄 Procesando Soruahá (ID: 416)...
⚠️ Advertencia: No se encontró la sección básica para ID 416
⚠️ No se encontraron entradas para Soruahá (ID 416)
📄 Procesando Central Aymara (ID: 98)...
✅ 191 entradas extraídas para ID 98
📄 Procesando Awa Pit (ID: 418)...
⚠️ Advertencia: No se encontró la sección básica para ID 418
⚠️ No se encontraron entradas para Awa Pit (ID 418)
📄 Procesando Cha'palaa (ID: 350)...
✅ 191 entradas extraídas para ID 350
📄 Procesando Tsafiki (ID: 417)...
⚠️ Advertencia: No se encontró la sección básica para ID 417
⚠️ No se encontraron entradas para Tsafiki (ID 417)
📄 Procesando Bora (ID: 68)...
✅ 191 entradas extraídas para ID 68
📄 Procesando Muinane (ID: 69)...
✅ 191 entradas extraídas para ID 69
📄 Procesando Jebero (ID: 420)...
⚠️ Advertencia: No se encontró la sección básica para ID 420
⚠️ No se encontraron entradas para Jebero (ID 420)
📄 Procesando Shawi (ID: 419)...
⚠️ Advertencia: No se encontró la sección básica para ID 419
⚠️ No se encontraron entradas para Shawi (ID 419)
📄 Procesando Akawaio (ID: 70)...
✅ 191 entradas extraídas para ID 70
📄 Procesando Akawaio/Ingariko dialect (ID: 71)...
✅ 191 entradas extraídas para ID 71
📄 Procesando Apalai (ID: 351)...
✅ 191 entradas extraídas para ID 351
📄 Procesando Carijona (ID: 72)...
✅ 192 entradas extraídas para ID 72
📄 Procesando Eñepa (ID: 73)...
✅ 192 entradas extraídas para ID 73
📄 Procesando Kalapalo (ID: 354)...
✅ 191 entradas extraídas para ID 354
📄 Procesando Kariña (ID: 421)...
✅ 192 entradas extraídas para ID 421
📄 Procesando Makiritare (ID: 258)...
✅ 191 entradas extraídas para ID 258
📄 Procesando Makushi (ID: 75)...
✅ 192 entradas extraídas para ID 75
📄 Procesando Mapoyo (ID: 76)...
✅ 191 entradas extraídas para ID 76
📄 Procesando Maquiritari (ID: 422)...
⚠️ Advertencia: No se encontró la sección básica para ID 422
⚠️ No se encontraron entradas para Maquiritari (ID 422)
📄 Procesando Panare (ID: 424)...
⚠️ Advertencia: No se encontró la sección básica para ID 424
⚠️ No se encontraron entradas para Panare (ID 424)
📄 Procesando Pemon (ID: 77)...
✅ 192 entradas extraídas para ID 77
📄 Procesando Tiriyó (ID: 353)...
✅ 191 entradas extraídas para ID 353
📄 Procesando Trió (ID: 423)...
⚠️ Advertencia: No se encontró la sección básica para ID 423
⚠️ No se encontraron entradas para Trió (ID 423)
📄 Procesando Wai Wai (ID: 78)...
✅ 191 entradas extraídas para ID 78
📄 Procesando Waimiri Atroari (ID: 79)...
✅ 191 entradas extraídas para ID 79
📄 Procesando Wayana (ID: 352)...
✅ 191 entradas extraídas para ID 352
📄 Procesando Yabarana (ID: 80)...
✅ 191 entradas extraídas para ID 80
📄 Procesando Yukpa (ID: 81)...
✅ 191 entradas extraídas para ID 81
📄 Procesando Kitemoka (ID: 427)...
⚠️ Advertencia: No se encontró la sección básica para ID 427
⚠️ No se encontraron entradas para Kitemoka (ID 427)
📄 Procesando Moré (ID: 425)...
⚠️ Advertencia: No se encontró la sección básica para ID 425
⚠️ No se encontraron entradas para Moré (ID 425)
📄 Procesando Tapakura (ID: 426)...
⚠️ Advertencia: No se encontró la sección básica para ID 426
⚠️ No se encontraron entradas para Tapakura (ID 426)
📄 Procesando Wari (ID: 371)...
✅ 191 entradas extraídas para ID 371
📄 Procesando Barí (ID: 355)...
✅ 191 entradas extraídas para ID 355
📄 Procesando Boruca (ID: 430)...
⚠️ Advertencia: No se encontró la sección básica para ID 430
⚠️ No se encontraron entradas para Boruca (ID 430)
📄 Procesando Bribri (ID: 432)...
⚠️ Advertencia: No se encontró la sección básica para ID 432
⚠️ No se encontraron entradas para Bribri (ID 432)
📄 Procesando Cabecar (ID: 83)...
⚠️ Advertencia: No se encontró la sección básica para ID 83
⚠️ No se encontraron entradas para Cabecar (ID 83)
📄 Procesando Damana (ID: 84)...
⚠️ Advertencia: No se encontró la sección básica para ID 84
⚠️ No se encontraron entradas para Damana (ID 84)
📄 Procesando Dorasque (ID: 431)...
⚠️ Advertencia: No se encontró la sección básica para ID 431
⚠️ No se encontraron entradas para Dorasque (ID 431)
📄 Procesando Guatuso (ID: 476)...
⚠️ Advertencia: No se encontró la sección básica para ID 476
⚠️ No se encontraron entradas para Guatuso (ID 476)
📄 Procesando Guaymí (ID: 88)...
⚠️ Advertencia: No se encontró la sección básica para ID 88
⚠️ No se encontraron entradas para Guaymí (ID 88)
📄 Procesando Guna (ID: 262)...
⚠️ Advertencia: No se encontró la sección básica para ID 262
⚠️ No se encontraron entradas para Guna (ID 262)
📄 Procesando Ika (ID: 85)...
⚠️ Advertencia: No se encontró la sección básica para ID 85
⚠️ No se encontraron entradas para Ika (ID 85)
📄 Procesando Kogi (ID: 86)...
⚠️ Advertencia: No se encontró la sección básica para ID 86
⚠️ No se encontraron entradas para Kogi (ID 86)
📄 Procesando Muisca (ID: 82)...
✅ 191 entradas extraídas para ID 82
📄 Procesando Naso (ID: 263)...
⚠️ Advertencia: No se encontró la sección básica para ID 263
⚠️ No se encontraron entradas para Naso (ID 263)
📄 Procesando Pech (ID: 428)...
⚠️ Advertencia: No se encontró la sección básica para ID 428
⚠️ No se encontraron entradas para Pech (ID 428)
📄 Procesando Rama (ID: 429)...
⚠️ Advertencia: No se encontró la sección básica para ID 429
⚠️ No se encontraron entradas para Rama (ID 429)
📄 Procesando Tunebo (ID: 477)...
⚠️ Advertencia: No se encontró la sección básica para ID 477
⚠️ No se encontraron entradas para Tunebo (ID 477)
📄 Procesando Aguaruna (ID: 114)...
✅ 191 entradas extraídas para ID 114
📄 Procesando Ashuar (ID: 115)...
✅ 191 entradas extraídas para ID 115
📄 Procesando Huambisa (ID: 116)...
✅ 191 entradas extraídas para ID 116
📄 Procesando Shiwiar (ID: 479)...
⚠️ Advertencia: No se encontró la sección básica para ID 479
⚠️ No se encontraron entradas para Shiwiar (ID 479)
📄 Procesando Shuar (ID: 478)...
⚠️ Advertencia: No se encontró la sección básica para ID 478
⚠️ No se encontraron entradas para Shuar (ID 478)
📄 Procesando Embera (ID: 434)...
⚠️ Advertencia: No se encontró la sección básica para ID 434
⚠️ No se encontraron entradas para Embera (ID 434)
📄 Procesando Epena (ID: 356)...
✅ 191 entradas extraídas para ID 356
📄 Procesando Northern Emberá (ID: 90)...
✅ 191 entradas extraídas para ID 90
📄 Procesando Waunana (ID: 87)...
⚠️ Advertencia: No se encontró la sección básica para ID 87
⚠️ No se encontraron entradas para Waunana (ID 87)
📄 Procesando Selknam (ID: 401)...
✅ 191 entradas extraídas para ID 401
📄 Procesando Tehuelche (ID: 402)...
✅ 191 entradas extraídas para ID 402
📄 Procesando Cuiva (ID: 92)...
✅ 191 entradas extraídas para ID 92
📄 Procesando Guayabero (ID: 93)...
✅ 191 entradas extraídas para ID 93
📄 Procesando Macaguan (ID: 94)...
✅ 191 entradas extraídas para ID 94
📄 Procesando Playero (ID: 95)...
✅ 191 entradas extraídas para ID 95
📄 Procesando Sikuani (ID: 96)...
✅ 192 entradas extraídas para ID 96
📄 Procesando Mocoví (ID: 389)...
✅ 191 entradas extraídas para ID 389
📄 Procesando Pilagá (ID: 390)...
✅ 191 entradas extraídas para ID 390
📄 Procesando Toba (ID: 391)...
✅ 191 entradas extraídas para ID 391
📄 Procesando Amarakaeri (ID: 436)...
⚠️ Advertencia: No se encontró la sección básica para ID 436
⚠️ No se encontraron entradas para Amarakaeri (ID 436)
📄 Procesando Huachapaeri (ID: 435)...
⚠️ Advertencia: No se encontró la sección básica para ID 435
⚠️ No se encontraron entradas para Huachapaeri (ID 435)
📄 Procesando A'ɨwa (ID: 480)...
⚠️ Advertencia: No se encontró la sección básica para ID 480
⚠️ No se encontraron entradas para A'ɨwa (ID 480)
📄 Procesando Aikanã (ID: 439)...
⚠️ Advertencia: No se encontró la sección básica para ID 439
⚠️ No se encontraron entradas para Aikanã (ID 439)
📄 Procesando Andoke (ID: 97)...
✅ 191 entradas extraídas para ID 97
📄 Procesando Arutani (ID: 66)...
✅ 191 entradas extraídas para ID 66
📄 Procesando Camsa (ID: 99)...
✅ 191 entradas extraídas para ID 99
📄 Procesando Candoshi-Shapra (ID: 100)...
✅ 191 entradas extraídas para ID 100
📄 Procesando Cayuvava (ID: 377)...
✅ 191 entradas extraídas para ID 377
📄 Procesando Cofán (ID: 101)...
✅ 191 entradas extraídas para ID 101
📄 Procesando Hodï (ID: 102)...
✅ 192 entradas extraídas para ID 102
📄 Procesando Itonama (ID: 378)...
✅ 191 entradas extraídas para ID 378
📄 Procesando Kanoê (ID: 440)...
⚠️ Advertencia: No se encontró la sección básica para ID 440
⚠️ No se encontraron entradas para Kanoê (ID 440)
📄 Procesando Kwazá (ID: 379)...
✅ 191 entradas extraídas para ID 379
📄 Procesando Máku (ID: 104)...
✅ 191 entradas extraídas para ID 104
📄 Procesando Mosetén-Chimané (ID: 380)...
✅ 191 entradas extraídas para ID 380
📄 Procesando Movima (ID: 381)...
✅ 191 entradas extraídas para ID 381
📄 Procesando Muniche (ID: 437)...
⚠️ Advertencia: No se encontró la sección básica para ID 437
⚠️ No se encontraron entradas para Muniche (ID 437)
📄 Procesando Omurano (ID: 438)...
⚠️ Advertencia: No se encontró la sección básica para ID 438
⚠️ No se encontraron entradas para Omurano (ID 438)
📄 Procesando Páez (ID: 106)...
✅ 191 entradas extraídas para ID 106
📄 Procesando Puinave (ID: 107)...
✅ 191 entradas extraídas para ID 107
📄 Procesando Pumé (ID: 108)...
✅ 191 entradas extraídas para ID 108
📄 Procesando Sape (ID: 67)...
✅ 191 entradas extraídas para ID 67
📄 Procesando Taushiro (ID: 109)...
✅ 191 entradas extraídas para ID 109
📄 Procesando Tinigua (ID: 111)...
✅ 191 entradas extraídas para ID 111
📄 Procesando Trumai (ID: 382)...
✅ 191 entradas extraídas para ID 382
📄 Procesando Urarina (ID: 112)...
✅ 191 entradas extraídas para ID 112
📄 Procesando Waorani (ID: 103)...
✅ 192 entradas extraídas para ID 103
📄 Procesando Warao (ID: 113)...
✅ 191 entradas extraídas para ID 113
📄 Procesando Yurakare (ID: 441)...
⚠️ Advertencia: No se encontró la sección básica para ID 441
⚠️ No se encontraron entradas para Yurakare (ID 441)
📄 Procesando Kakua (ID: 117)...
✅ 192 entradas extraídas para ID 117
📄 Procesando Nukak (ID: 118)...
✅ 192 entradas extraídas para ID 118
📄 Procesando Kanamarí (ID: 442)...
✅ 197 entradas extraídas para ID 442
📄 Procesando Qawasqar (ID: 400)...
✅ 191 entradas extraídas para ID 400
📄 Procesando Arikapu (ID: 444)...
⚠️ Advertencia: No se encontró la sección básica para ID 444
⚠️ No se encontraron entradas para Arikapu (ID 444)
📄 Procesando Canela (ID: 385)...
✅ 191 entradas extraídas para ID 385
📄 Procesando Djeoromitxi (ID: 387)...
✅ 191 entradas extraídas para ID 387
📄 Procesando Kaingang (ID: 91)...
✅ 191 entradas extraídas para ID 91
📄 Procesando Karajá (ID: 386)...
✅ 191 entradas extraídas para ID 386
📄 Procesando Rikbaktsa (ID: 443)...
⚠️ Advertencia: No se encontró la sección básica para ID 443
⚠️ No se encontraron entradas para Rikbaktsa (ID 443)
📄 Procesando Suyá (ID: 384)...
✅ 191 entradas extraídas para ID 384
📄 Procesando Lengua (ID: 392)...
✅ 191 entradas extraídas para ID 392
📄 Procesando Sanapaná/Dialect Angaité (ID: 393)...
✅ 191 entradas extraídas para ID 393
📄 Procesando Sanapaná/Dialect Enlhet (ID: 394)...
✅ 191 entradas extraídas para ID 394
📄 Procesando Chorote, Iyojwa'ja (ID: 396)...
✅ 191 entradas extraídas para ID 396
📄 Procesando Maca (ID: 397)...
✅ 191 entradas extraídas para ID 397
📄 Procesando Nivaclé (ID: 398)...
✅ 191 entradas extraídas para ID 398
📄 Procesando Wichí Lhamtés Güisnay (ID: 395)...
✅ 191 entradas extraídas para ID 395
📄 Procesando Miskitu (ID: 433)...
⚠️ Advertencia: No se encontró la sección básica para ID 433
⚠️ No se encontraron entradas para Miskitu (ID 433)
📄 Procesando Dâw (ID: 119)...
✅ 192 entradas extraídas para ID 119
📄 Procesando Hup (ID: 120)...
✅ 192 entradas extraídas para ID 120
📄 Procesando Nadëb/Rio Negro dialect (ID: 121)...
✅ 191 entradas extraídas para ID 121
📄 Procesando Nadëb/Roçado dialect (ID: 122)...
✅ 191 entradas extraídas para ID 122
📄 Procesando Yuhup (ID: 123)...
✅ 192 entradas extraídas para ID 123
📄 Procesando Sabane (ID: 445)...
⚠️ Advertencia: No se encontró la sección básica para ID 445
⚠️ No se encontraron entradas para Sabane (ID 445)
📄 Procesando Amawaka (ID: 451)...
⚠️ Advertencia: No se encontró la sección básica para ID 451
⚠️ No se encontraron entradas para Amawaka (ID 451)
📄 Procesando Chácobo (ID: 362)...
✅ 191 entradas extraídas para ID 362
📄 Procesando Kakataibo (ID: 357)...
✅ 191 entradas extraídas para ID 357
📄 Procesando Kapanawa (ID: 448)...
⚠️ Advertencia: No se encontró la sección básica para ID 448
⚠️ No se encontraron entradas para Kapanawa (ID 448)
📄 Procesando Kashibo (ID: 447)...
⚠️ Advertencia: No se encontró la sección básica para ID 447
⚠️ No se encontraron entradas para Kashibo (ID 447)
📄 Procesando Katukina (ID: 358)...
✅ 191 entradas extraídas para ID 358
📄 Procesando Kaxarari (ID: 449)...
⚠️ Advertencia: No se encontró la sección básica para ID 449
⚠️ No se encontraron entradas para Kaxarari (ID 449)
📄 Procesando Marubo (ID: 446)...
⚠️ Advertencia: No se encontró la sección básica para ID 446
⚠️ No se encontraron entradas para Marubo (ID 446)
📄 Procesando Matis (ID: 487)...
⚠️ Advertencia: No se encontró la sección básica para ID 487
⚠️ No se encontraron entradas para Matis (ID 487)
📄 Procesando Matses (ID: 124)...
✅ 191 entradas extraídas para ID 124
📄 Procesando Pacahuara (ID: 359)...
✅ 191 entradas extraídas para ID 359
📄 Procesando Shipibo-Konibo (ID: 360)...
✅ 191 entradas extraídas para ID 360
📄 Procesando Yaminahua (ID: 361)...
✅ 191 entradas extraídas para ID 361
📄 Procesando Yagua (ID: 125)...
✅ 191 entradas extraídas para ID 125
📄 Procesando Ingá (ID: 126)...
✅ 191 entradas extraídas para ID 126
📄 Procesando Napo Lowland Quichua (ID: 127)...
✅ 191 entradas extraídas para ID 127
📄 Procesando Quechua Ayacuchano (ID: 128)...
✅ 191 entradas extraídas para ID 128
📄 Procesando Southern Pastaza Quechua (ID: 129)...
✅ 191 entradas extraídas para ID 129
📄 Procesando Mako (ID: 452)...
⚠️ Advertencia: No se encontró la sección básica para ID 452
⚠️ No se encontraron entradas para Mako (ID 452)
📄 Procesando Piaroa (ID: 130)...
✅ 191 entradas extraídas para ID 130
📄 Procesando Sáliva (ID: 363)...
✅ 191 entradas extraídas para ID 363
📄 Procesando Araona (ID: 372)...
✅ 191 entradas extraídas para ID 372
📄 Procesando Cavineña (ID: 375)...
✅ 191 entradas extraídas para ID 375
📄 Procesando Ese Ejja (ID: 373)...
✅ 191 entradas extraídas para ID 373
📄 Procesando Ese Ejja/Huarayo (ID: 403)...
✅ 191 entradas extraídas para ID 403
📄 Procesando Tacana (ID: 374)...
✅ 191 entradas extraídas para ID 374
📄 Procesando Tikuna (ID: 110)...
✅ 191 entradas extraídas para ID 110
📄 Procesando Bará (ID: 131)...
✅ 191 entradas extraídas para ID 131
📄 Procesando Barasano (ID: 132)...
✅ 191 entradas extraídas para ID 132
📄 Procesando Carapana (ID: 133)...
✅ 191 entradas extraídas para ID 133
📄 Procesando Cubeo (ID: 134)...
✅ 192 entradas extraídas para ID 134
📄 Procesando Desano (ID: 135)...
✅ 192 entradas extraídas para ID 135
📄 Procesando Koreguaje (ID: 146)...
✅ 191 entradas extraídas para ID 146
📄 Procesando Kotiria (ID: 144)...
✅ 192 entradas extraídas para ID 144
📄 Procesando Kueretu (ID: 453)...
⚠️ Advertencia: No se encontró la sección básica para ID 453
⚠️ No se encontraron entradas para Kueretu (ID 453)
📄 Procesando Maihiki (ID: 147)...
✅ 192 entradas extraídas para ID 147
📄 Procesando Makuna (ID: 136)...
✅ 191 entradas extraídas para ID 136
📄 Procesando Secoya (ID: 148)...
✅ 191 entradas extraídas para ID 148
📄 Procesando Siona (ID: 149)...
✅ 191 entradas extraídas para ID 149
📄 Procesando Siriano (ID: 138)...
✅ 191 entradas extraídas para ID 138
📄 Procesando Tanimuca (ID: 139)...
✅ 191 entradas extraídas para ID 139
📄 Procesando Tatuyo (ID: 140)...
✅ 191 entradas extraídas para ID 140

In [5]:
import pandas as pd

output_csv_path = "basic_vocabulary_full.csv"

try:
    df = pd.read_csv(output_csv_path)
    print("Column names:")
    print(df.columns.tolist())
    print("\nFirst 5 rows:")
    display(df.head())
except FileNotFoundError:
    print(f"Error: The file '{output_csv_path}' was not found. Please make sure the previous step completed successfully.")
except Exception as e:
    print(f"An error occurred while reading the CSV file: {e}")

Column names:
['Family', 'Language', 'ID', 'Gloss Link', 'Gloss', 'Orthographic Form', 'Phonemicized Form', 'Gloss as in Source', 'Etymology Code', 'Proto-Form', 'Proto-Language', 'Loan Source', 'Wanderwort Status', 'Etyma Set', 'Etymology Notes', 'General Notes', 'Source']

First 5 rows:

,Family,Language,ID,Gloss Link,Gloss,Orthographic Form,Phonemicized Form,Gloss as in Source,Etymology Code,Proto-Form,Proto-Language,Loan Source,Wanderwort Status,Etyma Set,Etymology Notes,General Notes,Source
Araucanian,Mapudungun,265,/lexical/feature/352,above,"encima, arriba",acima,location,NaN,NaN,wente,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Araucanian,Mapudungun,265,/lexical/feature/355,and,y,e,grammar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Araucanian,Mapudungun,265,/lexical/feature/359,ash,ceniza(s),cinzas,environment,NaN,NaN,ṭ͡ʀufken,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Araucanian,Mapudungun,265,/lexical/feature/360,at,"en, a","em, a",location,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Araucanian,Mapudungun,265,/lexical/feature/361,back,espalda,costas,body,NaN,NaN,furi,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
import pandas as pd

output_csv_path = "basic_vocabulary_full.csv"

try:
    df = pd.read_csv(output_csv_path)
    print("Column names:")
    print(df.columns.tolist())
    print("\nFirst 5 rows:")
    display(df.head())
except FileNotFoundError:
    print(f"Error: The file '{output_csv_path}' was not found. Please make sure the previous step completed successfully.")
except Exception as e:
    print(f"An error occurred while reading the CSV file: {e}")

Column names:
['Family', 'Language', 'ID', 'Gloss Link', 'All Glosses', 'Orthographic Form', 'Phonemicized Form', 'Gloss as in Source', 'Etymology Code', 'Proto-Form', 'Proto-Language', 'Loan Source', 'Wanderwort Status', 'Etyma Set', 'Etymology Notes', 'General Notes', 'Source']

First 5 rows:

,Family,Language,ID,Gloss Link,All Glosses,Orthographic Form,Phonemicized Form,Gloss as in Source,Etymology Code,Proto-Form,Proto-Language,Loan Source,Wanderwort Status,Etyma Set,Etymology Notes,General Notes,Source
Araucanian,Mapudungun,265,/lexical/feature/352,above,"encima, arriba",acima,location,NaN,NaN,wente,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Araucanian,Mapudungun,265,/lexical/feature/355,and,y,e,grammar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Araucanian,Mapudungun,265,/lexical/feature/359,ash,ceniza(s),cinzas,environment,NaN,NaN,ṭ͡ʀufken,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Araucanian,Mapudungun,265,/lexical/feature/360,at,"en, a","em, a",location,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Araucanian,Mapudungun,265,/lexical/feature/361,back,espalda,costas,body,NaN,NaN,furi,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
import pandas as pd

output_csv_path = "basic_vocabulary_full.csv"

try:
    df = pd.read_csv(output_csv_path)
    print("Column names:")
    print(df.columns.tolist())
    print("\nFirst 5 rows:")
    display(df.head())
except FileNotFoundError:
    print(f"Error: The file '{output_csv_path}' was not found. Please make sure the previous step completed successfully.")
except Exception as e:
    print(f"An error occurred while reading the CSV file: {e}")

Column names:
['Family', 'Language', 'ID', 'Gloss Link', 'English Gloss', 'Spanish Gloss', 'Portuguese Gloss', 'Orthographic Form', 'Phonemicized Form', 'Gloss as in Source', 'Etymology Code', 'Proto-Form', 'Proto-Language', 'Loan Source', 'Wanderwort Status', 'Etyma Set', 'Etymology Notes', 'General Notes', 'Source']

First 5 rows:

,Family,Language,ID,Gloss Link,English Gloss,Spanish Gloss,Portuguese Gloss,Orthographic Form,Phonemicized Form,Gloss as in Source,Etymology Code,Proto-Form,Proto-Language,Loan Source,Wanderwort Status,Etyma Set,Etymology Notes,General Notes,Source
Araucanian,Mapudungun,265,/lexical/feature/352,above,NaN,NaN,"encima, arriba",acima,location,NaN,NaN,wente,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Araucanian,Mapudungun,265,/lexical/feature/355,and,NaN,NaN,y,e,grammar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Araucanian,Mapudungun,265,/lexical/feature/359,ash,NaN,NaN,ceniza(s),cinzas,environment,NaN,NaN,ṭ͡ʀufken,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Araucanian,Mapudungun,265,/lexical/feature/360,at,NaN,NaN,"en, a","em, a",location,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Araucanian,Mapudungun,265,/lexical/feature/361,back,NaN,NaN,espalda,costas,body,NaN,NaN,furi,NaN,NaN,NaN,NaN,NaN,NaN,NaN