In [ ]:
!pip install lingpy
from lingpy import sequence

Requirement already satisfied: lingpy in /usr/local/lib/python3.12/dist-packages (2.6.13)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from lingpy) (2.0.2)
Requirement already satisfied: appdirs in /usr/local/lib/python3.12/dist-packages (from lingpy) (1.4.4)
Requirement already satisfied: networkx>=2.3 in /usr/local/lib/python3.12/dist-packages (from lingpy) (3.5)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from lingpy) (4.67.1)
Requirement already satisfied: csvw>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from lingpy) (3.7.0)
Requirement already satisfied: clldutils>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from lingpy) (3.24.2)
Requirement already satisfied: pycldf>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from lingpy) (1.43.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from lingpy) (5.4.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from clldutils>=2.8.0->lingpy) (2.9.0.post0)
Requirement already satisfied: tabulate>=0.7.7 in /usr/local/lib/python3.12/dist-packages (from clldutils>=2.8.0->lingpy) (0.9.0)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from clldutils>=2.8.0->lingpy) (6.10.1)
Requirement already satisfied: attrs>=18.1.0 in /usr/local/lib/python3.12/dist-packages (from clldutils>=2.8.0->lingpy) (25.4.0)
Requirement already satisfied: bibtexparser>=2.0.0b4 in /usr/local/lib/python3.12/dist-packages (from clldutils>=2.8.0->lingpy) (2.0.0b8)
Requirement already satisfied: pylatexenc in /usr/local/lib/python3.12/dist-packages (from clldutils>=2.8.0->lingpy) (2.10)
Requirement already satisfied: markdown in /usr/local/lib/python3.12/dist-packages (from clldutils>=2.8.0->lingpy) (3.9)
Requirement already satisfied: markupsafe in /usr/local/lib/python3.12/dist-packages (from clldutils>=2.8.0->lingpy) (3.0.3)
Requirement already satisfied: isodate in /usr/local/lib/python3.12/dist-packages (from csvw>=1.5.6->lingpy) (0.7.2)
Requirement already satisfied: rfc3986<2 in /usr/local/lib/python3.12/dist-packages (from csvw>=1.5.6->lingpy) (1.5.0)
Requirement already satisfied: uritemplate>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from csvw>=1.5.6->lingpy) (4.2.0)
Requirement already satisfied: babel in /usr/local/lib/python3.12/dist-packages (from csvw>=1.5.6->lingpy) (2.17.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from csvw>=1.5.6->lingpy) (2.32.4)
Requirement already satisfied: language-tags in /usr/local/lib/python3.12/dist-packages (from csvw>=1.5.6->lingpy) (1.2.0)
Requirement already satisfied: rdflib in /usr/local/lib/python3.12/dist-packages (from csvw>=1.5.6->lingpy) (7.2.1)
Requirement already satisfied: termcolor in /usr/local/lib/python3.12/dist-packages (from csvw>=1.5.6->lingpy) (3.1.0)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.12/dist-packages (from csvw>=1.5.6->lingpy) (4.25.1)
Requirement already satisfied: simplepybtex in /usr/local/lib/python3.12/dist-packages (from pycldf>=1.7.0->lingpy) (0.1.0)
Requirement already satisfied: newick in /usr/local/lib/python3.12/dist-packages (from pycldf>=1.7.0->lingpy) (1.10.0)
Requirement already satisfied: commonnexus>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from pycldf>=1.7.0->lingpy) (1.9.2)
Requirement already satisfied: python-frontmatter in /usr/local/lib/python3.12/dist-packages (from pycldf>=1.7.0->lingpy) (1.1.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from pycldf>=1.7.0->lingpy) (6.0.3)
Requirement already satisfied: jmespath in /usr/local/lib/python3.12/dist-packages (from pycldf>=1.7.0->lingpy) (1.0.1)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema->csvw>=1.5.6->lingpy) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema->csvw>=1.5.6->lingpy) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema->csvw>=1.5.6->lingpy) (0.27.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->clldutils>=2.8.0->lingpy) (1.17.0)
Requirement already satisfied: pyparsing<4,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from rdflib->csvw>=1.5.6->lingpy) (3.2.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->csvw>=1.5.6->lingpy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->csvw>=1.5.6->lingpy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->csvw>=1.5.6->lingpy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->csvw>=1.5.6->lingpy) (2025.10.5)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema->csvw>=1.5.6->lingpy) (4.15.0)

In [ ]:
import pandas as pd
import glob

file_list = glob.glob('/content/*.tsv')

dataframes = {}
for file_path in file_list:
    df_name = file_path.split('/')[-1].split('.')[0]
    dataframes[df_name] = pd.read_csv(file_path, sep='\t')

for df_name, df in dataframes.items():
    print(f"DataFrame: {df_name}")
    display(df.head())

DataFrame: p-nadahupan-concepticon_processed

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,beiju,MANIOC BREAD,407.0,Proto-Nadahupan,nada1235,Naduhupan,p'âʔ,p 'â ʔ
1,comida,FOOD,256.0,Proto-Nadahupan,nada1235,Naduhupan,wêtʼ,w ê tʼ
2,goma,NaN,NaN,Proto-Nadahupan,nada1235,Naduhupan,dũ̂h,d ũ̂ h
3,girino,TADPOLE,3979.0,Proto-Nadahupan,nada1235,Naduhupan,dudud,d u d u d
4,rã,FROG,503.0,Proto-Nadahupan,nada1235,Naduhupan,cʼâ jo,NaN

DataFrame: p-chapacuran-concepticon

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM
0,chin,CHIN,1510.0,Proto-Chapacuran,chap1271,Chapakuran,hoɾam
1,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː
2,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː
3,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː
4,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː

DataFrame: p-guahiban-concepticon_processed

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,abdomen,BELLY,1251.0,Proto-Guahiban,guah1252,Guahiban,khotowita,k h o t o w i t a
1,Adam's apple,NaN,NaN,Proto-Guahiban,guah1252,Guahiban,kuaYbokará,k ua Y b o k a r á
2,Adam's apple,NaN,NaN,Proto-Guahiban,guah1252,Guahiban,batɨto,b a t ɨ t o
3,agouti,AGOUTI,313.0,Proto-Guahiban,guah1252,Guahiban,"bɨnɨ, bɨNɨ",NaN
4,all,ALL,98.0,Proto-Guahiban,guah1252,Guahiban,daxɨ́ta,d a x ɨ́ t a

DataFrame: p-chapacuran-concepticon_processed

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,chin,CHIN,1510.0,Proto-Chapacuran,chap1271,Chapakuran,hoɾam,h o ɾ a m
1,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː,j aː
2,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː,j aː
3,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː,j aː
4,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː,j aː

DataFrame: p-macro-je-concepticon

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM
0,jirau,NaN,NaN,Proto-Macro-Je,nucl1710,Macro-Jean,par°
1,braço,ARM,1673.0,Proto-Macro-Je,nucl1710,Macro-Jean,paj
2,braço,ARM,1673.0,Proto-Macro-Je,nucl1710,Macro-Jean,paj°
3,braço,ARM,1673.0,Proto-Macro-Je,nucl1710,Macro-Jean,paj
4,braço,ARM,1673.0,Proto-Macro-Je,nucl1710,Macro-Jean,paj°

DataFrame: p-quechuan-concepticon

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM
0,many,MANY,1198.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃka
1,many,MANY,1198.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃka
2,much,MANY,1198.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃka
3,much,MANY,1198.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃka
4,light,LIGHT (RADIATION),630.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃki

DataFrame: p-panoan-concepticon

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM
0,sun,SUN,1343.0,Proto-Panoan,pano1256,Panoan,βaɽi
1,star,STAR,1430.0,Proto-Panoan,pano1256,Panoan,wis
2,corn,MAIZE,506.0,Proto-Panoan,pano1256,Panoan,ʂɨki
3,to make,MAKE,734.0,Proto-Panoan,pano1256,Panoan,ʔak
4,to make,MAKE,734.0,Proto-Panoan,pano1256,Panoan,ʔak

DataFrame: p-chicham-concepticon

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM
0,caña de azúcar,SUGAR CANE,146.0,Proto-Shuar,jiva1245,Chicham,pagaata
1,huangana,COLLARED PECCARY,435.0,Proto-Shuar,jiva1245,Chicham,páki
2,tapir,TAPIR,312.0,Proto-Shuar,jiva1245,Chicham,pamáu
3,tapir,TAPIR,312.0,Proto-Shuar,jiva1245,Chicham,pamáu
4,sachavaca,TAPIR,312.0,Proto-Shuar,jiva1245,Chicham,pamáu

DataFrame: p-quechuan-concepticon_processed

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,many,MANY,1198.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃka,a t͡ʃ k a
1,many,MANY,1198.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃka,a t͡ʃ k a
2,much,MANY,1198.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃka,a t͡ʃ k a
3,much,MANY,1198.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃka,a t͡ʃ k a
4,light,LIGHT (RADIATION),630.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃki,NaN

DataFrame: p-chocoan-concepticon

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM
0,agua,WATER,948.0,Proto-Chocoan,choc1280,Chocoan,do
1,agua,WATER,948.0,Proto-Chocoan,choc1280,Chocoan,do
2,río,FLOWING BODY OF WATER,3311.0,Proto-Chocoan,choc1280,Chocoan,do
3,río,FLOWING BODY OF WATER,3311.0,Proto-Chocoan,choc1280,Chocoan,do
4,ahora,NOW,1376.0,Proto-Chocoan,choc1280,Chocoan,nãu

DataFrame: p-zaparoan-concepticon

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM
0,bee,BEE,665.0,Proto-Zaparoan,zapa1251,Zaparoan,ahapaka
1,bee,BEE,665.0,Proto-Zaparoan,zapa1251,Zaparoan,ahapaka
2,wasp,WASP,1517.0,Proto-Zaparoan,zapa1251,Zaparoan,ahapaka
3,wasp,WASP,1517.0,Proto-Zaparoan,zapa1251,Zaparoan,ahapaka
4,stick,STICK,1295.0,Proto-Zaparoan,zapa1251,Zaparoan,amaka

DataFrame: p-panoan-concepticon_processed

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,sun,SUN,1343.0,Proto-Panoan,pano1256,Panoan,βaɽi,β a ɽ i
1,star,STAR,1430.0,Proto-Panoan,pano1256,Panoan,wis,w i s
2,corn,MAIZE,506.0,Proto-Panoan,pano1256,Panoan,ʂɨki,ʂ ɨ k i
3,to make,MAKE,734.0,Proto-Panoan,pano1256,Panoan,ʔak,ʔ a k
4,to make,MAKE,734.0,Proto-Panoan,pano1256,Panoan,ʔak,ʔ a k

DataFrame: p-chicham-concepticon_processed

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,caña de azúcar,SUGAR CANE,146.0,Proto-Shuar,jiva1245,Chicham,pagaata,p a g aa t a
1,huangana,COLLARED PECCARY,435.0,Proto-Shuar,jiva1245,Chicham,páki,p á k i
2,tapir,TAPIR,312.0,Proto-Shuar,jiva1245,Chicham,pamáu,p a m áu
3,tapir,TAPIR,312.0,Proto-Shuar,jiva1245,Chicham,pamáu,p a m áu
4,sachavaca,TAPIR,312.0,Proto-Shuar,jiva1245,Chicham,pamáu,p a m áu

DataFrame: p-chapacuran-concepticon_temp

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM
0,chin,CHIN,1510.0,Proto-Chapacuran,chap1271,Chapakuran,hoɾam
1,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː
2,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː
3,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː
4,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː

DataFrame: p-chibchan-concepticon_processed

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuíkI,ˈk uí k I
1,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuí,NaN
2,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuíkI,ˈk uí k I
3,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuí,NaN
4,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuíkI,ˈk uí k I

DataFrame: p-guahiban-concepticon

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM
0,abdomen,BELLY,1251.0,Proto-Guahiban,guah1252,Guahiban,khotowita
1,Adam's apple,NaN,NaN,Proto-Guahiban,guah1252,Guahiban,kuaYbokará
2,Adam's apple,NaN,NaN,Proto-Guahiban,guah1252,Guahiban,batɨto
3,agouti,AGOUTI,313.0,Proto-Guahiban,guah1252,Guahiban,"bɨnɨ, bɨNɨ"
4,all,ALL,98.0,Proto-Guahiban,guah1252,Guahiban,daxɨ́ta

DataFrame: p-guaicuru-concepticon_processed

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,pestaña,EYELASH,1540.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀde,aˀ d e
1,conducir,DRIVE,741.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀdéga,aˀ d é g a
2,verde,GREEN,1425.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀdéla,aˀ d é l a
3,verde,GREEN,1425.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀdéla,aˀ d é l a
4,verde,GREEN,1425.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀdéla,aˀ d é l a

DataFrame: p-nadahupan-concepticon

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM
0,beiju,MANIOC BREAD,407.0,Proto-Nadahupan,nada1235,Naduhupan,p'âʔ
1,comida,FOOD,256.0,Proto-Nadahupan,nada1235,Naduhupan,wêtʼ
2,goma,NaN,NaN,Proto-Nadahupan,nada1235,Naduhupan,dũ̂h
3,girino,TADPOLE,3979.0,Proto-Nadahupan,nada1235,Naduhupan,dudud
4,rã,FROG,503.0,Proto-Nadahupan,nada1235,Naduhupan,cʼâ jo

DataFrame: p-arawakan-concepticon_processed

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,head,HEAD,1256.0,Proto-Arawakan,araw1281,Arawakan,kɨwɨ,k ɨ w ɨ
1,eye,EYE,1248.0,Proto-Arawakan,araw1281,Arawakan,lʊkɨ,l ʊ k ɨ
2,ear,EAR,1247.0,Proto-Arawakan,araw1281,Arawakan,dakenai,d a k e n ai
3,nose,NOSE,1221.0,Proto-Arawakan,araw1281,Arawakan,kiri,k i r i
4,mouth,MOUTH,674.0,Proto-Arawakan,araw1281,Arawakan,kanakɨ,k a n a k ɨ

DataFrame: p-arawakan-concepticon

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM
0,head,HEAD,1256.0,Proto-Arawakan,araw1281,Arawakan,kɨwɨ
1,eye,EYE,1248.0,Proto-Arawakan,araw1281,Arawakan,lʊkɨ
2,ear,EAR,1247.0,Proto-Arawakan,araw1281,Arawakan,dakenai
3,nose,NOSE,1221.0,Proto-Arawakan,araw1281,Arawakan,kiri
4,mouth,MOUTH,674.0,Proto-Arawakan,araw1281,Arawakan,kanakɨ

DataFrame: p-aymaran-concepticon_processed

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,old,OLD (AGED),2112,Proto-Aymara,ayma1253,Aymaran,at͡ʃa,NaN
1,cactus species,CACTUS,2595,Proto-Aymara,ayma1253,Aymaran,at͡ʃuma,a t͡ʃ u m a
2,large,BIG,1202,Proto-Aymara,ayma1253,Aymaran,atʂa,a t ʂ a
3,many,MANY,1198,Proto-Aymara,ayma1253,Aymaran,atʂi,a t ʂ i
4,many,MANY,1198,Proto-Aymara,ayma1253,Aymaran,atʂi,a t ʂ i

DataFrame: p-guaicuru-concepticon

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM
0,pestaña,EYELASH,1540.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀde
1,conducir,DRIVE,741.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀdéga
2,verde,GREEN,1425.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀdéla
3,verde,GREEN,1425.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀdéla
4,verde,GREEN,1425.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀdéla

DataFrame: p-chocoan-concepticon_processed

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,agua,WATER,948.0,Proto-Chocoan,choc1280,Chocoan,do,d o
1,agua,WATER,948.0,Proto-Chocoan,choc1280,Chocoan,do,d o
2,río,FLOWING BODY OF WATER,3311.0,Proto-Chocoan,choc1280,Chocoan,do,d o
3,río,FLOWING BODY OF WATER,3311.0,Proto-Chocoan,choc1280,Chocoan,do,d o
4,ahora,NOW,1376.0,Proto-Chocoan,choc1280,Chocoan,nãu,n ãu

DataFrame: p-matacoan-concepticon

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM
0,estar borracho,DRUNK,1463.0,Proto-Matacoan,mata1289,Matacoan,hwum
1,tú bebes,NaN,NaN,Proto-Matacoan,mata1289,Matacoan,hl
2,maíz,MAIZE,506.0,Proto-Matacoan,mata1289,Matacoan,iphatha
3,tía,AUNT,1272.0,Proto-Matacoan,mata1289,Matacoan,itho
4,arco,ARCH,876.0,Proto-Matacoan,mata1289,Matacoan,lutshe

DataFrame: p-matacoan-concepticon_processed

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,estar borracho,DRUNK,1463.0,Proto-Matacoan,mata1289,Matacoan,hwum,h w u m
1,tú bebes,NaN,NaN,Proto-Matacoan,mata1289,Matacoan,hl,h l
2,maíz,MAIZE,506.0,Proto-Matacoan,mata1289,Matacoan,iphatha,i p h a t h a
3,tía,AUNT,1272.0,Proto-Matacoan,mata1289,Matacoan,itho,i t h o
4,arco,ARCH,876.0,Proto-Matacoan,mata1289,Matacoan,lutshe,l u t s h e

DataFrame: p-aymaran-concepticon

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM
0,old,OLD (AGED),2112,Proto-Aymara,ayma1253,Aymaran,at͡ʃa
1,cactus species,CACTUS,2595,Proto-Aymara,ayma1253,Aymaran,at͡ʃuma
2,large,BIG,1202,Proto-Aymara,ayma1253,Aymaran,atʂa
3,many,MANY,1198,Proto-Aymara,ayma1253,Aymaran,atʂi
4,many,MANY,1198,Proto-Aymara,ayma1253,Aymaran,atʂi

DataFrame: p-zaparoan-concepticon_processed

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,bee,BEE,665.0,Proto-Zaparoan,zapa1251,Zaparoan,ahapaka,a h a p a k a
1,bee,BEE,665.0,Proto-Zaparoan,zapa1251,Zaparoan,ahapaka,a h a p a k a
2,wasp,WASP,1517.0,Proto-Zaparoan,zapa1251,Zaparoan,ahapaka,a h a p a k a
3,wasp,WASP,1517.0,Proto-Zaparoan,zapa1251,Zaparoan,ahapaka,a h a p a k a
4,stick,STICK,1295.0,Proto-Zaparoan,zapa1251,Zaparoan,amaka,a m a k a

DataFrame: p-chibchan-concepticon

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM
0,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuíkI
1,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuí
2,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuíkI
3,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuí
4,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuíkI

DataFrame: p-macro-je-concepticon_processed

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,jirau,NaN,NaN,Proto-Macro-Je,nucl1710,Macro-Jean,par°,p a r °
1,braço,ARM,1673.0,Proto-Macro-Je,nucl1710,Macro-Jean,paj,NaN
2,braço,ARM,1673.0,Proto-Macro-Je,nucl1710,Macro-Jean,paj°,NaN
3,braço,ARM,1673.0,Proto-Macro-Je,nucl1710,Macro-Jean,paj,NaN
4,braço,ARM,1673.0,Proto-Macro-Je,nucl1710,Macro-Jean,paj°,NaN

In [ ]:
# Remove leading and trailing spaces from the 'FORM' column
for df_name, df in dataframes.items():
    dataframes[df_name]['FORM'] = dataframes[df_name]['FORM'].astype(str).str.strip()
    print(f"Trimmed spaces in 'FORM' column for DataFrame: {df_name}")

print("\nLeading and trailing spaces removed from 'FORM' column in all dataframes.")

Trimmed spaces in 'FORM' column for DataFrame: p-nadahupan-concepticon_processed
Trimmed spaces in 'FORM' column for DataFrame: p-chapacuran-concepticon
Trimmed spaces in 'FORM' column for DataFrame: p-guahiban-concepticon_processed
Trimmed spaces in 'FORM' column for DataFrame: p-chapacuran-concepticon_processed
Trimmed spaces in 'FORM' column for DataFrame: p-macro-je-concepticon
Trimmed spaces in 'FORM' column for DataFrame: p-quechuan-concepticon
Trimmed spaces in 'FORM' column for DataFrame: p-panoan-concepticon
Trimmed spaces in 'FORM' column for DataFrame: p-chicham-concepticon
Trimmed spaces in 'FORM' column for DataFrame: p-quechuan-concepticon_processed
Trimmed spaces in 'FORM' column for DataFrame: p-chocoan-concepticon
Trimmed spaces in 'FORM' column for DataFrame: p-zaparoan-concepticon
Trimmed spaces in 'FORM' column for DataFrame: p-panoan-concepticon_processed
Trimmed spaces in 'FORM' column for DataFrame: p-chicham-concepticon_processed
Trimmed spaces in 'FORM' column for DataFrame: p-chapacuran-concepticon_temp
Trimmed spaces in 'FORM' column for DataFrame: p-chibchan-concepticon_processed
Trimmed spaces in 'FORM' column for DataFrame: p-guahiban-concepticon
Trimmed spaces in 'FORM' column for DataFrame: p-guaicuru-concepticon_processed
Trimmed spaces in 'FORM' column for DataFrame: p-nadahupan-concepticon
Trimmed spaces in 'FORM' column for DataFrame: p-arawakan-concepticon_processed
Trimmed spaces in 'FORM' column for DataFrame: p-arawakan-concepticon
Trimmed spaces in 'FORM' column for DataFrame: p-aymaran-concepticon_processed
Trimmed spaces in 'FORM' column for DataFrame: p-guaicuru-concepticon
Trimmed spaces in 'FORM' column for DataFrame: p-chocoan-concepticon_processed
Trimmed spaces in 'FORM' column for DataFrame: p-matacoan-concepticon
Trimmed spaces in 'FORM' column for DataFrame: p-matacoan-concepticon_processed
Trimmed spaces in 'FORM' column for DataFrame: p-aymaran-concepticon
Trimmed spaces in 'FORM' column for DataFrame: p-zaparoan-concepticon_processed
Trimmed spaces in 'FORM' column for DataFrame: p-chibchan-concepticon
Trimmed spaces in 'FORM' column for DataFrame: p-macro-je-concepticon_processed

Leading and trailing spaces removed from 'FORM' column in all dataframes.

In [ ]:
import pandas as pd
import glob
import lingpy # Import top-level lingpy
import os

# Assuming dataframes is already loaded from the previous cell

# Process all dataframes in the dictionary
for df_name, df in dataframes.items():
    # Apply the ipa2tokens function from lingpy.sequence with error handling
    segmented_tokens = []
    for form in df['FORM']:
        try:
            # Convert to string and attempt to segment
            tokens = lingpy.sequence.ipa2tokens(str(form))
            segmented_tokens.append(tokens)
        except (ValueError, IndexError) as e: # Catch both ValueError and IndexError
            # Handle cases with invalid input or segmentation issues
            print(f"Warning: Could not segment form '{form}' in {df_name} due to error: {e}")
            segmented_tokens.append(None) # Assign None for problematic entries

    dataframes[df_name]['TOKENS'] = segmented_tokens

    # Convert the list of tokens into a space-separated string, handling None values
    # The join operation handles empty lists correctly, resulting in an empty string
    dataframes[df_name]['TOKENS'] = [' '.join(tokens) if tokens is not None else '' for tokens in dataframes[df_name]['TOKENS']]


    print(f"Processed DataFrame: {df_name} with TOKENS column")
    display(dataframes[df_name].head())

    # Save the processed DataFrame to a new TSV file
    output_filename = f"{df_name}_processed.tsv"
    dataframes[df_name].to_csv(output_filename, sep='\t', index=False)
    print(f"Saved processed DataFrame to: {output_filename}")

print("\nAll dataframes have been processed and saved.")

Warning: Could not segment form 'cʼâ jo' in p-nadahupan-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ja ʔo' in p-nadahupan-concepticon_processed due to error: Input must not contain spaces
Processed DataFrame: p-nadahupan-concepticon_processed with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,beiju,MANIOC BREAD,407.0,Proto-Nadahupan,nada1235,Naduhupan,p'âʔ,p 'â ʔ
1,comida,FOOD,256.0,Proto-Nadahupan,nada1235,Naduhupan,wêtʼ,w ê tʼ
2,goma,NaN,NaN,Proto-Nadahupan,nada1235,Naduhupan,dũ̂h,d ũ̂ h
3,girino,TADPOLE,3979.0,Proto-Nadahupan,nada1235,Naduhupan,dudud,d u d u d
4,rã,FROG,503.0,Proto-Nadahupan,nada1235,Naduhupan,cʼâ jo,

Saved processed DataFrame to: p-nadahupan-concepticon_processed_processed.tsv
Warning: Could not segment form 'kat, ɾat' in p-chapacuran-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'tɾan tɾan' in p-chapacuran-concepticon due to error: Input must not contain spaces
Processed DataFrame: p-chapacuran-concepticon with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,chin,CHIN,1510.0,Proto-Chapacuran,chap1271,Chapakuran,hoɾam,h o ɾ a m
1,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː,j aː
2,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː,j aː
3,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː,j aː
4,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː,j aː

Saved processed DataFrame to: p-chapacuran-concepticon_processed.tsv
Warning: Could not segment form 'bɨnɨ, bɨNɨ' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'tsóNi preGuahiban' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'kuyani preGuahiban' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'sirito preGuahiban' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'síne, síNe' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'xáne, xáNe' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'kuhúnawa, kuhúNawa' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'iso, nawa' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'dáina, dáiNa' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'wa, Nasítsi' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'húmetane, húmetaNe' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'xáina, xáiNa' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'pakuénia, pakuéNia' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'yapítane, yapítaNe' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ãmataonápia, ãmataoNápia' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'hanahawa, haNahawa' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'katénapa, katéNapa' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'méne, méNe' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'méne, méNe' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'méne, méNe' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'méne, méNe' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ióne, ióNe' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'naxɨ́ana, naxɨ́aNa' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'nahunatabi xáin' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'náehava, haewa' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'náehava, haewa' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'náehava, haewa' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'náehava, haewa' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'náehava, haewa' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'náehava, haewa' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'éta hóta' in p-guahiban-concepticon_processed due to error: Input must not contain spaces
Processed DataFrame: p-guahiban-concepticon_processed with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,abdomen,BELLY,1251.0,Proto-Guahiban,guah1252,Guahiban,khotowita,k h o t o w i t a
1,Adam's apple,NaN,NaN,Proto-Guahiban,guah1252,Guahiban,kuaYbokará,k ua Y b o k a r á
2,Adam's apple,NaN,NaN,Proto-Guahiban,guah1252,Guahiban,batɨto,b a t ɨ t o
3,agouti,AGOUTI,313.0,Proto-Guahiban,guah1252,Guahiban,"bɨnɨ, bɨNɨ",
4,all,ALL,98.0,Proto-Guahiban,guah1252,Guahiban,daxɨ́ta,d a x ɨ́ t a

Saved processed DataFrame to: p-guahiban-concepticon_processed_processed.tsv
Warning: Could not segment form 'kat, ɾat' in p-chapacuran-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'tɾan tɾan' in p-chapacuran-concepticon_processed due to error: Input must not contain spaces
Processed DataFrame: p-chapacuran-concepticon_processed with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,chin,CHIN,1510.0,Proto-Chapacuran,chap1271,Chapakuran,hoɾam,h o ɾ a m
1,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː,j aː
2,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː,j aː
3,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː,j aː
4,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː,j aː

Saved processed DataFrame to: p-chapacuran-concepticon_processed_processed.tsv
Warning: Could not segment form '' in p-macro-je-concepticon due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon due to error: list index out of range
Warning: Could not segment form 'pi F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'mbâc F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'mbâc F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'mbâŋ NF' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'mbâŋ NF' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'mbu F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'mbur NF' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'mũ₁ F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'wĩ F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ru F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ja F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'jam NF' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ProtoJê Meridional jãnky' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ProtoJê Meridional jãnky' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'jot° F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'jo NF' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'je F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ji F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'kə F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'kər NF' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'kə F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'kər NF' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'kə F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'kər NF' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'kə F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'kər NF' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ŋgrê F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ŋgrê F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ŋgrê F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ŋgrê F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ũp F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ũ₁r F' in p-macro-je-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ñũ₁t° NF' in p-macro-je-concepticon due to error: Input must not contain spaces
Processed DataFrame: p-macro-je-concepticon with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,jirau,NaN,NaN,Proto-Macro-Je,nucl1710,Macro-Jean,par°,p a r °
1,braço,ARM,1673.0,Proto-Macro-Je,nucl1710,Macro-Jean,paj,p a j
2,braço,ARM,1673.0,Proto-Macro-Je,nucl1710,Macro-Jean,paj°,p a j °
3,braço,ARM,1673.0,Proto-Macro-Je,nucl1710,Macro-Jean,paj,p a j
4,braço,ARM,1673.0,Proto-Macro-Je,nucl1710,Macro-Jean,paj°,p a j °

Saved processed DataFrame to: p-macro-je-concepticon_processed.tsv
Processed DataFrame: p-quechuan-concepticon with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,many,MANY,1198.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃka,a t͡ʃ k a
1,many,MANY,1198.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃka,a t͡ʃ k a
2,much,MANY,1198.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃka,a t͡ʃ k a
3,much,MANY,1198.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃka,a t͡ʃ k a
4,light,LIGHT (RADIATION),630.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃki,a t͡ʃ k i

Saved processed DataFrame to: p-quechuan-concepticon_processed.tsv
Warning: Could not segment form 'tʃiʔi mapo' in p-panoan-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'tʃiʔi mapo' in p-panoan-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'hɨnɨ ʔino' in p-panoan-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'mɨkɨrɨ kʷaya' in p-panoan-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'nawa βaʔi' in p-panoan-concepticon due to error: Input must not contain spaces
Processed DataFrame: p-panoan-concepticon with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,sun,SUN,1343.0,Proto-Panoan,pano1256,Panoan,βaɽi,β a ɽ i
1,star,STAR,1430.0,Proto-Panoan,pano1256,Panoan,wis,w i s
2,corn,MAIZE,506.0,Proto-Panoan,pano1256,Panoan,ʂɨki,ʂ ɨ k i
3,to make,MAKE,734.0,Proto-Panoan,pano1256,Panoan,ʔak,ʔ a k
4,to make,MAKE,734.0,Proto-Panoan,pano1256,Panoan,ʔak,ʔ a k

Saved processed DataFrame to: p-panoan-concepticon_processed.tsv
Warning: Could not segment form 'ku yú' in p-chicham-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'shikí tu' in p-chicham-concepticon due to error: Input must not contain spaces
Processed DataFrame: p-chicham-concepticon with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,caña de azúcar,SUGAR CANE,146.0,Proto-Shuar,jiva1245,Chicham,pagaata,p a g aa t a
1,huangana,COLLARED PECCARY,435.0,Proto-Shuar,jiva1245,Chicham,páki,p á k i
2,tapir,TAPIR,312.0,Proto-Shuar,jiva1245,Chicham,pamáu,p a m áu
3,tapir,TAPIR,312.0,Proto-Shuar,jiva1245,Chicham,pamáu,p a m áu
4,sachavaca,TAPIR,312.0,Proto-Shuar,jiva1245,Chicham,pamáu,p a m áu

Saved processed DataFrame to: p-chicham-concepticon_processed.tsv
Processed DataFrame: p-quechuan-concepticon_processed with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,many,MANY,1198.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃka,a t͡ʃ k a
1,many,MANY,1198.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃka,a t͡ʃ k a
2,much,MANY,1198.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃka,a t͡ʃ k a
3,much,MANY,1198.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃka,a t͡ʃ k a
4,light,LIGHT (RADIATION),630.0,Proto-Quechuan,quec1387,Quechuan,at͡ʃki,a t͡ʃ k i

Saved processed DataFrame to: p-quechuan-concepticon_processed_processed.tsv
Warning: Could not segment form 'heˈbe, hẽˈbe' in p-chocoan-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ˈneme ˈhõbɯ' in p-chocoan-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'daˈbu kaˈɾa' in p-chocoan-concepticon due to error: Input must not contain spaces
Processed DataFrame: p-chocoan-concepticon with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,agua,WATER,948.0,Proto-Chocoan,choc1280,Chocoan,do,d o
1,agua,WATER,948.0,Proto-Chocoan,choc1280,Chocoan,do,d o
2,río,FLOWING BODY OF WATER,3311.0,Proto-Chocoan,choc1280,Chocoan,do,d o
3,río,FLOWING BODY OF WATER,3311.0,Proto-Chocoan,choc1280,Chocoan,do,d o
4,ahora,NOW,1376.0,Proto-Chocoan,choc1280,Chocoan,nãu,n ãu

Saved processed DataFrame to: p-chocoan-concepticon_processed.tsv
Processed DataFrame: p-zaparoan-concepticon with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,bee,BEE,665.0,Proto-Zaparoan,zapa1251,Zaparoan,ahapaka,a h a p a k a
1,bee,BEE,665.0,Proto-Zaparoan,zapa1251,Zaparoan,ahapaka,a h a p a k a
2,wasp,WASP,1517.0,Proto-Zaparoan,zapa1251,Zaparoan,ahapaka,a h a p a k a
3,wasp,WASP,1517.0,Proto-Zaparoan,zapa1251,Zaparoan,ahapaka,a h a p a k a
4,stick,STICK,1295.0,Proto-Zaparoan,zapa1251,Zaparoan,amaka,a m a k a

Saved processed DataFrame to: p-zaparoan-concepticon_processed.tsv
Warning: Could not segment form 'tʃiʔi mapo' in p-panoan-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'tʃiʔi mapo' in p-panoan-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'hɨnɨ ʔino' in p-panoan-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'mɨkɨrɨ kʷaya' in p-panoan-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'nawa βaʔi' in p-panoan-concepticon_processed due to error: Input must not contain spaces
Processed DataFrame: p-panoan-concepticon_processed with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,sun,SUN,1343.0,Proto-Panoan,pano1256,Panoan,βaɽi,β a ɽ i
1,star,STAR,1430.0,Proto-Panoan,pano1256,Panoan,wis,w i s
2,corn,MAIZE,506.0,Proto-Panoan,pano1256,Panoan,ʂɨki,ʂ ɨ k i
3,to make,MAKE,734.0,Proto-Panoan,pano1256,Panoan,ʔak,ʔ a k
4,to make,MAKE,734.0,Proto-Panoan,pano1256,Panoan,ʔak,ʔ a k

Saved processed DataFrame to: p-panoan-concepticon_processed_processed.tsv
Warning: Could not segment form 'ku yú' in p-chicham-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'shikí tu' in p-chicham-concepticon_processed due to error: Input must not contain spaces
Processed DataFrame: p-chicham-concepticon_processed with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,caña de azúcar,SUGAR CANE,146.0,Proto-Shuar,jiva1245,Chicham,pagaata,p a g aa t a
1,huangana,COLLARED PECCARY,435.0,Proto-Shuar,jiva1245,Chicham,páki,p á k i
2,tapir,TAPIR,312.0,Proto-Shuar,jiva1245,Chicham,pamáu,p a m áu
3,tapir,TAPIR,312.0,Proto-Shuar,jiva1245,Chicham,pamáu,p a m áu
4,sachavaca,TAPIR,312.0,Proto-Shuar,jiva1245,Chicham,pamáu,p a m áu

Saved processed DataFrame to: p-chicham-concepticon_processed_processed.tsv
Warning: Could not segment form 'kat, ɾat' in p-chapacuran-concepticon_temp due to error: Input must not contain spaces
Warning: Could not segment form 'tɾan tɾan' in p-chapacuran-concepticon_temp due to error: Input must not contain spaces
Processed DataFrame: p-chapacuran-concepticon_temp with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,chin,CHIN,1510.0,Proto-Chapacuran,chap1271,Chapakuran,hoɾam,h o ɾ a m
1,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː,j aː
2,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː,j aː
3,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː,j aː
4,to say,SAY,1458.0,Proto-Chapacuran,chap1271,Chapakuran,jaː,j aː

Saved processed DataFrame to: p-chapacuran-concepticon_temp_processed.tsv
Processed DataFrame: p-chibchan-concepticon_processed with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuíkI,ˈk uí k I
1,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuí,ˈk uí
2,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuíkI,ˈk uí k I
3,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuí,ˈk uí
4,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuíkI,ˈk uí k I

Saved processed DataFrame to: p-chibchan-concepticon_processed_processed.tsv
Warning: Could not segment form 'bɨnɨ, bɨNɨ' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'tsóNi preGuahiban' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'kuyani preGuahiban' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'sirito preGuahiban' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'síne, síNe' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'xáne, xáNe' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'kuhúnawa, kuhúNawa' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'iso, nawa' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'dáina, dáiNa' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'wa, Nasítsi' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'húmetane, húmetaNe' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'xáina, xáiNa' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'pakuénia, pakuéNia' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'yapítane, yapítaNe' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ãmataonápia, ãmataoNápia' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'hanahawa, haNahawa' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'katénapa, katéNapa' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'méne, méNe' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'méne, méNe' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'méne, méNe' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'méne, méNe' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ióne, ióNe' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'naxɨ́ana, naxɨ́aNa' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'nahunatabi xáin' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'náehava, haewa' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'náehava, haewa' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'náehava, haewa' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'náehava, haewa' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'náehava, haewa' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'náehava, haewa' in p-guahiban-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'éta hóta' in p-guahiban-concepticon due to error: Input must not contain spaces
Processed DataFrame: p-guahiban-concepticon with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,abdomen,BELLY,1251.0,Proto-Guahiban,guah1252,Guahiban,khotowita,k h o t o w i t a
1,Adam's apple,NaN,NaN,Proto-Guahiban,guah1252,Guahiban,kuaYbokará,k ua Y b o k a r á
2,Adam's apple,NaN,NaN,Proto-Guahiban,guah1252,Guahiban,batɨto,b a t ɨ t o
3,agouti,AGOUTI,313.0,Proto-Guahiban,guah1252,Guahiban,"bɨnɨ, bɨNɨ",
4,all,ALL,98.0,Proto-Guahiban,guah1252,Guahiban,daxɨ́ta,d a x ɨ́ t a

Saved processed DataFrame to: p-guahiban-concepticon_processed.tsv
Warning: Could not segment form 'aqa, aqˑaqa' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'aqa, aqˑaqa' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'aqa, aqˑaqa' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'aqa, aqˑaqa' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'aqakˀa fem., aqaikˀa masc.' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'epˀa, epˀáqa' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'epˀa, epˀáqa' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'epˀa, epˀáqa' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'epˀa, epˀáqa' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'etʃjódʔo ~ etʃjódo' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'oˀjaq, oˀjak' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'pwatik ~ pwadik' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'pwatik ~ pwadik' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'pwatik ~ pwadik' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'pwatik ~ pwadik' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'pwatik ~ pwadik' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'pwatik ~ pwadik' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'pwatik ~ pwadik' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'pwatik ~ pwadik' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'pwatik ~ pwadik' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ˀwága, ˀwágaˑˀwága' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ʔVtˀek, ʔVtˀaqa' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'awa ~ aqawa' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'alat ~ aqalat' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ʔáji ~ aqʔáji' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'aqa ~ qo' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ʔat ~ aqʔat' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ʔawéʔke ~ tˀaweʔke' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ʔawéʔke ~ tˀaweʔke' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ʔawéʔke ~ tˀaweʔke' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ʔawéʔke ~ tˀaweʔke' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'aqate ~ ate' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'éˀn ~ ʔéˀn' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ej ~j' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'J_V ~ ji' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form '_V ~ qoː' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form '_V ~ qa:' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'eˀl ~ ˀ1' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'en ~ n' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'o ~ ó  ʔo' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'Vdi C' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form '_ ~ di V' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'qa, qˀa' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ʔo ~ o' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'C ~ etʃ ~ tʃ' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form '_C ~ j' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'qod ~ qo' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'aqawa ~ ʔawa' in p-guaicuru-concepticon_processed due to error: Input must not contain spaces
Processed DataFrame: p-guaicuru-concepticon_processed with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,pestaña,EYELASH,1540.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀde,aˀ d e
1,conducir,DRIVE,741.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀdéga,aˀ d é g a
2,verde,GREEN,1425.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀdéla,aˀ d é l a
3,verde,GREEN,1425.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀdéla,aˀ d é l a
4,verde,GREEN,1425.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀdéla,aˀ d é l a

Saved processed DataFrame to: p-guaicuru-concepticon_processed_processed.tsv
Warning: Could not segment form 'cʼâ jo' in p-nadahupan-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ja ʔo' in p-nadahupan-concepticon due to error: Input must not contain spaces
Processed DataFrame: p-nadahupan-concepticon with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,beiju,MANIOC BREAD,407.0,Proto-Nadahupan,nada1235,Naduhupan,p'âʔ,p 'â ʔ
1,comida,FOOD,256.0,Proto-Nadahupan,nada1235,Naduhupan,wêtʼ,w ê tʼ
2,goma,NaN,NaN,Proto-Nadahupan,nada1235,Naduhupan,dũ̂h,d ũ̂ h
3,girino,TADPOLE,3979.0,Proto-Nadahupan,nada1235,Naduhupan,dudud,d u d u d
4,rã,FROG,503.0,Proto-Nadahupan,nada1235,Naduhupan,cʼâ jo,

Saved processed DataFrame to: p-nadahupan-concepticon_processed.tsv
Processed DataFrame: p-arawakan-concepticon_processed with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,head,HEAD,1256.0,Proto-Arawakan,araw1281,Arawakan,kɨwɨ,k ɨ w ɨ
1,eye,EYE,1248.0,Proto-Arawakan,araw1281,Arawakan,lʊkɨ,l ʊ k ɨ
2,ear,EAR,1247.0,Proto-Arawakan,araw1281,Arawakan,dakenai,d a k e n ai
3,nose,NOSE,1221.0,Proto-Arawakan,araw1281,Arawakan,kiri,k i r i
4,mouth,MOUTH,674.0,Proto-Arawakan,araw1281,Arawakan,kanakɨ,k a n a k ɨ

Saved processed DataFrame to: p-arawakan-concepticon_processed_processed.tsv
Processed DataFrame: p-arawakan-concepticon with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,head,HEAD,1256.0,Proto-Arawakan,araw1281,Arawakan,kɨwɨ,k ɨ w ɨ
1,eye,EYE,1248.0,Proto-Arawakan,araw1281,Arawakan,lʊkɨ,l ʊ k ɨ
2,ear,EAR,1247.0,Proto-Arawakan,araw1281,Arawakan,dakenai,d a k e n ai
3,nose,NOSE,1221.0,Proto-Arawakan,araw1281,Arawakan,kiri,k i r i
4,mouth,MOUTH,674.0,Proto-Arawakan,araw1281,Arawakan,kanakɨ,k a n a k ɨ

Saved processed DataFrame to: p-arawakan-concepticon_processed.tsv
Processed DataFrame: p-aymaran-concepticon_processed with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,old,OLD (AGED),2112,Proto-Aymara,ayma1253,Aymaran,at͡ʃa,a t͡ʃ a
1,cactus species,CACTUS,2595,Proto-Aymara,ayma1253,Aymaran,at͡ʃuma,a t͡ʃ u m a
2,large,BIG,1202,Proto-Aymara,ayma1253,Aymaran,atʂa,a t ʂ a
3,many,MANY,1198,Proto-Aymara,ayma1253,Aymaran,atʂi,a t ʂ i
4,many,MANY,1198,Proto-Aymara,ayma1253,Aymaran,atʂi,a t ʂ i

Saved processed DataFrame to: p-aymaran-concepticon_processed_processed.tsv
Warning: Could not segment form 'aqa, aqˑaqa' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'aqa, aqˑaqa' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'aqa, aqˑaqa' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'aqa, aqˑaqa' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'aqakˀa fem., aqaikˀa masc.' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'epˀa, epˀáqa' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'epˀa, epˀáqa' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'epˀa, epˀáqa' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'epˀa, epˀáqa' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'etʃjódʔo ~ etʃjódo' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'oˀjaq, oˀjak' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'pwatik ~ pwadik' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'pwatik ~ pwadik' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'pwatik ~ pwadik' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'pwatik ~ pwadik' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'pwatik ~ pwadik' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'pwatik ~ pwadik' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'pwatik ~ pwadik' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'pwatik ~ pwadik' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'pwatik ~ pwadik' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ˀwága, ˀwágaˑˀwága' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ʔVtˀek, ʔVtˀaqa' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'awa ~ aqawa' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'alat ~ aqalat' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ʔáji ~ aqʔáji' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'aqa ~ qo' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ʔat ~ aqʔat' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ʔawéʔke ~ tˀaweʔke' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ʔawéʔke ~ tˀaweʔke' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ʔawéʔke ~ tˀaweʔke' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ʔawéʔke ~ tˀaweʔke' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'aqate ~ ate' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'éˀn ~ ʔéˀn' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ej ~j' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'J_V ~ ji' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form '_V ~ qoː' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form '_V ~ qa:' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'eˀl ~ ˀ1' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'en ~ n' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'o ~ ó  ʔo' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'Vdi C' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form '_ ~ di V' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'qa, qˀa' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'ʔo ~ o' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'C ~ etʃ ~ tʃ' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form '_C ~ j' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'qod ~ qo' in p-guaicuru-concepticon due to error: Input must not contain spaces
Warning: Could not segment form 'aqawa ~ ʔawa' in p-guaicuru-concepticon due to error: Input must not contain spaces
Processed DataFrame: p-guaicuru-concepticon with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,pestaña,EYELASH,1540.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀde,aˀ d e
1,conducir,DRIVE,741.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀdéga,aˀ d é g a
2,verde,GREEN,1425.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀdéla,aˀ d é l a
3,verde,GREEN,1425.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀdéla,aˀ d é l a
4,verde,GREEN,1425.0,Proto-Guaicuru,guai1249,Guaicuruan,aˀdéla,aˀ d é l a

Saved processed DataFrame to: p-guaicuru-concepticon_processed.tsv
Warning: Could not segment form 'heˈbe, hẽˈbe' in p-chocoan-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ˈneme ˈhõbɯ' in p-chocoan-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'daˈbu kaˈɾa' in p-chocoan-concepticon_processed due to error: Input must not contain spaces
Processed DataFrame: p-chocoan-concepticon_processed with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,agua,WATER,948.0,Proto-Chocoan,choc1280,Chocoan,do,d o
1,agua,WATER,948.0,Proto-Chocoan,choc1280,Chocoan,do,d o
2,río,FLOWING BODY OF WATER,3311.0,Proto-Chocoan,choc1280,Chocoan,do,d o
3,río,FLOWING BODY OF WATER,3311.0,Proto-Chocoan,choc1280,Chocoan,do,d o
4,ahora,NOW,1376.0,Proto-Chocoan,choc1280,Chocoan,nãu,n ãu

Saved processed DataFrame to: p-chocoan-concepticon_processed_processed.tsv
Processed DataFrame: p-matacoan-concepticon with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,estar borracho,DRUNK,1463.0,Proto-Matacoan,mata1289,Matacoan,hwum,h w u m
1,tú bebes,NaN,NaN,Proto-Matacoan,mata1289,Matacoan,hl,h l
2,maíz,MAIZE,506.0,Proto-Matacoan,mata1289,Matacoan,iphatha,i p h a t h a
3,tía,AUNT,1272.0,Proto-Matacoan,mata1289,Matacoan,itho,i t h o
4,arco,ARCH,876.0,Proto-Matacoan,mata1289,Matacoan,lutshe,l u t s h e

Saved processed DataFrame to: p-matacoan-concepticon_processed.tsv
Processed DataFrame: p-matacoan-concepticon_processed with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,estar borracho,DRUNK,1463.0,Proto-Matacoan,mata1289,Matacoan,hwum,h w u m
1,tú bebes,NaN,NaN,Proto-Matacoan,mata1289,Matacoan,hl,h l
2,maíz,MAIZE,506.0,Proto-Matacoan,mata1289,Matacoan,iphatha,i p h a t h a
3,tía,AUNT,1272.0,Proto-Matacoan,mata1289,Matacoan,itho,i t h o
4,arco,ARCH,876.0,Proto-Matacoan,mata1289,Matacoan,lutshe,l u t s h e

Saved processed DataFrame to: p-matacoan-concepticon_processed_processed.tsv
Processed DataFrame: p-aymaran-concepticon with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,old,OLD (AGED),2112,Proto-Aymara,ayma1253,Aymaran,at͡ʃa,a t͡ʃ a
1,cactus species,CACTUS,2595,Proto-Aymara,ayma1253,Aymaran,at͡ʃuma,a t͡ʃ u m a
2,large,BIG,1202,Proto-Aymara,ayma1253,Aymaran,atʂa,a t ʂ a
3,many,MANY,1198,Proto-Aymara,ayma1253,Aymaran,atʂi,a t ʂ i
4,many,MANY,1198,Proto-Aymara,ayma1253,Aymaran,atʂi,a t ʂ i

Saved processed DataFrame to: p-aymaran-concepticon_processed.tsv
Processed DataFrame: p-zaparoan-concepticon_processed with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,bee,BEE,665.0,Proto-Zaparoan,zapa1251,Zaparoan,ahapaka,a h a p a k a
1,bee,BEE,665.0,Proto-Zaparoan,zapa1251,Zaparoan,ahapaka,a h a p a k a
2,wasp,WASP,1517.0,Proto-Zaparoan,zapa1251,Zaparoan,ahapaka,a h a p a k a
3,wasp,WASP,1517.0,Proto-Zaparoan,zapa1251,Zaparoan,ahapaka,a h a p a k a
4,stick,STICK,1295.0,Proto-Zaparoan,zapa1251,Zaparoan,amaka,a m a k a

Saved processed DataFrame to: p-zaparoan-concepticon_processed_processed.tsv
Processed DataFrame: p-chibchan-concepticon with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuíkI,ˈk uí k I
1,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuí,ˈk uí
2,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuíkI,ˈk uí k I
3,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuí,ˈk uí
4,arm,ARM OR HAND,2121.0,Proto-Chibchan,chib1249,Chibchan,ˈkuíkI,ˈk uí k I

Saved processed DataFrame to: p-chibchan-concepticon_processed.tsv
Warning: Could not segment form '' in p-macro-je-concepticon_processed due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon_processed due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon_processed due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon_processed due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon_processed due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon_processed due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon_processed due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon_processed due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon_processed due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon_processed due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon_processed due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon_processed due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon_processed due to error: list index out of range
Warning: Could not segment form '' in p-macro-je-concepticon_processed due to error: list index out of range
Warning: Could not segment form 'pi F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'mbâc F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'mbâc F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'mbâŋ NF' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'mbâŋ NF' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'mbu F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'mbur NF' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'mũ₁ F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'wĩ F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ru F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ja F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'jam NF' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ProtoJê Meridional jãnky' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ProtoJê Meridional jãnky' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'jot° F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'jo NF' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'je F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ji F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'kə F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'kər NF' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'kə F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'kər NF' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'kə F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'kər NF' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'kə F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'kər NF' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ŋgrê F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ŋgrê F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ŋgrê F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ŋgrê F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ũp F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ũ₁r F' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Warning: Could not segment form 'ñũ₁t° NF' in p-macro-je-concepticon_processed due to error: Input must not contain spaces
Processed DataFrame: p-macro-je-concepticon_processed with TOKENS column

,GLOSS,CONCEPTICON_GLOSS,CONCEPTICON_ID,LANGUAGE,GLOTTOCODE,FAMILY,FORM,TOKENS
0,jirau,NaN,NaN,Proto-Macro-Je,nucl1710,Macro-Jean,par°,p a r °
1,braço,ARM,1673.0,Proto-Macro-Je,nucl1710,Macro-Jean,paj,p a j
2,braço,ARM,1673.0,Proto-Macro-Je,nucl1710,Macro-Jean,paj°,p a j °
3,braço,ARM,1673.0,Proto-Macro-Je,nucl1710,Macro-Jean,paj,p a j
4,braço,ARM,1673.0,Proto-Macro-Je,nucl1710,Macro-Jean,paj°,p a j °

Saved processed DataFrame to: p-macro-je-concepticon_processed_processed.tsv

All dataframes have been processed and saved.

In [ ]:
import pandas as pd

# Concatenate all dataframes in the dictionary into a single dataframe
combined_df = pd.concat(dataframes.values(), ignore_index=True)

# Define the output filename for the combined dataframe
output_filename_combined = "all_processed_dataframes_combined.tsv"

# Save the combined dataframe to a TSV file
combined_df.to_csv(output_filename_combined, sep='\t', index=False)

print(f"All processed dataframes have been combined and saved to: {output_filename_combined}")

All processed dataframes have been combined and saved to: all_processed_dataframes_combined.tsv