# Task
Create Python code to load the CSV file "processed_vocabulary.csv" into a dataframe, remove all parentheses and whitespace characters from the 4th column, and display the updated dataframe.

## Load the data

### Subtask:
Load the `processed_vocabulary.csv` file into a pandas DataFrame.

**Reasoning**:
Load the CSV file into a pandas DataFrame.

In [18]:
import pandas as pd
df = pd.read_csv('processed_vocabulary.csv')

**Reasoning**:
Display the first few rows of the loaded DataFrame to verify the data was loaded correctly.

In [19]:
df.head()

        index      Family Language      Form
0  Araucanian  Mapudungun    above     wente
1  Araucanian  Mapudungun      ash  ṭ͡ʀufken
2  Araucanian  Mapudungun     back      furi
3  Araucanian  Mapudungun      bad      weθa
4  Araucanian  Mapudungun    belly    pɨṭ͡ʀa

## Process the data

### Subtask:
Strip parentheses and whitespace characters from the 4th column.

**Reasoning**:
Strip parentheses and whitespace characters from the 4th column.

In [20]:
df.iloc[:, 3] = df.iloc[:, 3].str.replace('[() ]', '', regex=True).str.strip()
display(df)

            index      Family  Language      Form
0      Araucanian  Mapudungun     above     wente
1      Araucanian  Mapudungun       ash  ṭ͡ʀufken
2      Araucanian  Mapudungun      back      furi
3      Araucanian  Mapudungun       bad      weθa
4      Araucanian  Mapudungun     belly    pɨṭ͡ʀa
...           ...         ...       ...       ...
36277    Zaparoan      Záparo       sun  yanawkʷa
36278    Zaparoan      Záparo  mountain   tuanaha
36279    Zaparoan      Záparo      hill   tuanaha
36280    Zaparoan      Záparo     green     nɨːka
36281    Zaparoan      Záparo       hot   upanaka

[36282 rows x 4 columns]

In [21]:
df.iloc[:, 3] = df.iloc[:, 3].str.replace('[1-9]', '', regex=True).str.strip()
display(df)

            index      Family  Language      Form
0      Araucanian  Mapudungun     above     wente
1      Araucanian  Mapudungun       ash  ṭ͡ʀufken
2      Araucanian  Mapudungun      back      furi
3      Araucanian  Mapudungun       bad      weθa
4      Araucanian  Mapudungun     belly    pɨṭ͡ʀa
...           ...         ...       ...       ...
36277    Zaparoan      Záparo       sun  yanawkʷa
36278    Zaparoan      Záparo  mountain   tuanaha
36279    Zaparoan      Záparo      hill   tuanaha
36280    Zaparoan      Záparo     green     nɨːka
36281    Zaparoan      Záparo       hot   upanaka

[36282 rows x 4 columns]

## Display the result

### Subtask:
Display the modified DataFrame to show the changes.

**Reasoning**:
Display the DataFrame to show the changes made in the previous step.

In [22]:
display(df)

            index      Family  Language      Form
0      Araucanian  Mapudungun     above     wente
1      Araucanian  Mapudungun       ash  ṭ͡ʀufken
2      Araucanian  Mapudungun      back      furi
3      Araucanian  Mapudungun       bad      weθa
4      Araucanian  Mapudungun     belly    pɨṭ͡ʀa
...           ...         ...       ...       ...
36277    Zaparoan      Záparo       sun  yanawkʷa
36278    Zaparoan      Záparo  mountain   tuanaha
36279    Zaparoan      Záparo      hill   tuanaha
36280    Zaparoan      Záparo     green     nɨːka
36281    Zaparoan      Záparo       hot   upanaka

[36282 rows x 4 columns]

## Summary:

### Data Analysis Key Findings

*   The `processed_vocabulary.csv` file was successfully loaded into a pandas DataFrame.
*   Parentheses and leading/trailing whitespace characters were successfully removed from the entries in the fourth column of the DataFrame.
*   The final DataFrame contains 36282 rows and 4 columns.

### Insights or Next Steps

*   The cleaned fourth column can now be used for further linguistic analysis or processing.
*   Consider applying similar cleaning steps to other columns if they contain unwanted characters or whitespace.

In [23]:
df.to_csv('processed_vocabulary_cleaned.csv', index=False)